// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addStudentApplicationCollege = `-- name: AddStudentApplicationCollege :exec
INSERT INTO student_application_colleges (application_id, college_id) VALUES ($1, $2)
`

type AddStudentApplicationCollegeParams struct {
	ApplicationID uuid.UUID
	CollegeID     uuid.UUID
}

func (q *Queries) AddStudentApplicationCollege(ctx context.Context, arg AddStudentApplicationCollegeParams) error {
	_, err := q.db.Exec(ctx, addStudentApplicationCollege, arg.ApplicationID, arg.CollegeID)
	return err
}

const clearStudentApplicationColleges = `-- name: ClearStudentApplicationColleges :exec
DELETE FROM student_application_colleges WHERE application_id = $1
`

func (q *Queries) ClearStudentApplicationColleges(ctx context.Context, applicationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearStudentApplicationColleges, applicationID)
	return err
}

const countApplicationsByStatus = `-- name: CountApplicationsByStatus :many
SELECT s.name AS status_name, count(a.id) AS total
FROM application_statuses s
LEFT JOIN student_applications a
       ON a.application_status_id = s.id AND a.deleted_at IS NULL
GROUP BY s.name
ORDER BY s.name
`

type CountApplicationsByStatusRow struct {
	StatusName string
	Total      int64
}

func (q *Queries) CountApplicationsByStatus(ctx context.Context) ([]CountApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countApplicationsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountApplicationsByStatusRow{}
	for rows.Next() {
		var i CountApplicationsByStatusRow
		if err := rows.Scan(&i.StatusName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countStudentApplications = `-- name: CountStudentApplications :one
SELECT count(*) FROM student_applications a
WHERE a.deleted_at IS NULL
  AND a.branch_id = $1
  AND ($2::text = ''
       OR a.application_name ILIKE '%'||$2||'%'
       OR a.application_number ILIKE '%'||$2||'%'
       OR EXISTS (
           SELECT 1 FROM student_application_colleges sac 
           JOIN colleges c ON sac.college_id = c.id
           WHERE sac.application_id = a.id AND c.name ILIKE '%'||$2||'%'
       ))
`

type CountStudentApplicationsParams struct {
	BranchID uuid.UUID
	Filter   string
}

func (q *Queries) CountStudentApplications(ctx context.Context, arg CountStudentApplicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentApplications, arg.BranchID, arg.Filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentApplication = `-- name: CreateStudentApplication :one
INSERT INTO student_applications (
    student_id, branch_id, application_type_id, application_status_id,
    application_number, application_name, last_date, applied_date, submitted_date,
    form_type_id, portal_username, portal_password, remarks, created_by, updated_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
RETURNING id, student_id, application_type_id, application_status_id, application_number, application_name, last_date, applied_date, submitted_date, portal_username, portal_password, remarks, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, form_type_id, branch_id
`

type CreateStudentApplicationParams struct {
	StudentID           uuid.UUID
	BranchID            uuid.UUID
	ApplicationTypeID   uuid.UUID
	ApplicationStatusID uuid.UUID
	ApplicationNumber   *string
	ApplicationName     *string
	LastDate            *time.Time
	AppliedDate         *time.Time
	SubmittedDate       *time.Time
	FormTypeID          *uuid.UUID
	PortalUsername      *string
	PortalPassword      *string
	Remarks             *string
	CreatedBy           *int64
	UpdatedBy           *int64
}

func (q *Queries) CreateStudentApplication(ctx context.Context, arg CreateStudentApplicationParams) (StudentApplication, error) {
	row := q.db.QueryRow(ctx, createStudentApplication,
		arg.StudentID,
		arg.BranchID,
		arg.ApplicationTypeID,
		arg.ApplicationStatusID,
		arg.ApplicationNumber,
		arg.ApplicationName,
		arg.LastDate,
		arg.AppliedDate,
		arg.SubmittedDate,
		arg.FormTypeID,
		arg.PortalUsername,
		arg.PortalPassword,
		arg.Remarks,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i StudentApplication
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ApplicationTypeID,
		&i.ApplicationStatusID,
		&i.ApplicationNumber,
		&i.ApplicationName,
		&i.LastDate,
		&i.AppliedDate,
		&i.SubmittedDate,
		&i.PortalUsername,
		&i.PortalPassword,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.FormTypeID,
		&i.BranchID,
	)
	return i, err
}

const exportStudentApplications = `-- name: ExportStudentApplications :many
SELECT 
    a.id, a.student_id, a.application_type_id, a.application_status_id, a.application_number, a.application_name, a.last_date, a.applied_date, a.submitted_date, a.portal_username, a.portal_password, a.remarks, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at, a.deleted_by, a.form_type_id, a.branch_id,
    s.student_code,
    s.full_name AS student_name,
    t.name AS application_type_name,
    st.name AS application_status_name,
    f.name AS form_type_name
FROM student_applications a
JOIN students s ON s.id = a.student_id
LEFT JOIN application_types t ON t.id = a.application_type_id
LEFT JOIN application_statuses st ON st.id = a.application_status_id
LEFT JOIN form_types f ON f.id = a.form_type_id
WHERE a.deleted_at IS NULL
  AND ($1::text = ''
       OR a.application_name ILIKE '%'||$1||'%'
       OR a.application_number ILIKE '%'||$1||'%'
       OR EXISTS (
           SELECT 1 FROM student_application_colleges sac 
           JOIN colleges c ON sac.college_id = c.id
           WHERE sac.application_id = a.id AND c.name ILIKE '%'||$1||'%'
       ))
ORDER BY a.created_at DESC
`

type ExportStudentApplicationsRow struct {
	ID                    uuid.UUID
	StudentID             uuid.UUID
	ApplicationTypeID     uuid.UUID
	ApplicationStatusID   uuid.UUID
	ApplicationNumber     *string
	ApplicationName       *string
	LastDate              *time.Time
	AppliedDate           *time.Time
	SubmittedDate         *time.Time
	PortalUsername        *string
	PortalPassword        *string
	Remarks               *string
	CreatedBy             *int64
	UpdatedBy             *int64
	CreatedAt             time.Time
	UpdatedAt             time.Time
	DeletedAt             *time.Time
	DeletedBy             *int64
	FormTypeID            *uuid.UUID
	BranchID              uuid.UUID
	StudentCode           string
	StudentName           string
	ApplicationTypeName   *string
	ApplicationStatusName *string
	FormTypeName          *string
}

func (q *Queries) ExportStudentApplications(ctx context.Context, filter string) ([]ExportStudentApplicationsRow, error) {
	rows, err := q.db.Query(ctx, exportStudentApplications, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportStudentApplicationsRow{}
	for rows.Next() {
		var i ExportStudentApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ApplicationTypeID,
			&i.ApplicationStatusID,
			&i.ApplicationNumber,
			&i.ApplicationName,
			&i.LastDate,
			&i.AppliedDate,
			&i.SubmittedDate,
			&i.PortalUsername,
			&i.PortalPassword,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.FormTypeID,
			&i.BranchID,
			&i.StudentCode,
			&i.StudentName,
			&i.ApplicationTypeName,
			&i.ApplicationStatusName,
			&i.FormTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationsByStudent = `-- name: GetApplicationsByStudent :many
SELECT id, student_id, application_type_id, application_status_id, application_number, application_name, last_date, applied_date, submitted_date, portal_username, portal_password, remarks, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, form_type_id, branch_id FROM student_applications
WHERE student_id = $1 AND branch_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetApplicationsByStudentParams struct {
	StudentID uuid.UUID
	BranchID  uuid.UUID
}

func (q *Queries) GetApplicationsByStudent(ctx context.Context, arg GetApplicationsByStudentParams) ([]StudentApplication, error) {
	rows, err := q.db.Query(ctx, getApplicationsByStudent, arg.StudentID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentApplication{}
	for rows.Next() {
		var i StudentApplication
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ApplicationTypeID,
			&i.ApplicationStatusID,
			&i.ApplicationNumber,
			&i.ApplicationName,
			&i.LastDate,
			&i.AppliedDate,
			&i.SubmittedDate,
			&i.PortalUsername,
			&i.PortalPassword,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.FormTypeID,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationsByStudentsAndType = `-- name: GetApplicationsByStudentsAndType :many
SELECT id, student_id, application_type_id, application_status_id, application_number, application_name, last_date, applied_date, submitted_date, portal_username, portal_password, remarks, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, form_type_id, branch_id FROM student_applications 
WHERE application_type_id = $1 AND student_id = ANY($2::uuid[]) AND deleted_at IS NULL
`

type GetApplicationsByStudentsAndTypeParams struct {
	ApplicationTypeID uuid.UUID
	StudentIds        []uuid.UUID
}

func (q *Queries) GetApplicationsByStudentsAndType(ctx context.Context, arg GetApplicationsByStudentsAndTypeParams) ([]StudentApplication, error) {
	rows, err := q.db.Query(ctx, getApplicationsByStudentsAndType, arg.ApplicationTypeID, arg.StudentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentApplication{}
	for rows.Next() {
		var i StudentApplication
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ApplicationTypeID,
			&i.ApplicationStatusID,
			&i.ApplicationNumber,
			&i.ApplicationName,
			&i.LastDate,
			&i.AppliedDate,
			&i.SubmittedDate,
			&i.PortalUsername,
			&i.PortalPassword,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.FormTypeID,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollegesForApplication = `-- name: GetCollegesForApplication :many
SELECT c.id, c.tenant_id, c.name, c.created_at, c.updated_at, c.deleted_at, c.created_by, c.updated_by FROM colleges c
JOIN student_application_colleges sac ON sac.college_id = c.id
WHERE sac.application_id = $1
ORDER BY c.name
`

func (q *Queries) GetCollegesForApplication(ctx context.Context, applicationID uuid.UUID) ([]College, error) {
	rows, err := q.db.Query(ctx, getCollegesForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []College{}
	for rows.Next() {
		var i College
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollegesForApplications = `-- name: GetCollegesForApplications :many
SELECT sac.application_id, c.id, c.name 
FROM colleges c
JOIN student_application_colleges sac ON sac.college_id = c.id
WHERE sac.application_id = ANY($1::uuid[])
ORDER BY c.name
`

type GetCollegesForApplicationsRow struct {
	ApplicationID uuid.UUID
	ID            uuid.UUID
	Name          string
}

func (q *Queries) GetCollegesForApplications(ctx context.Context, applicationIds []uuid.UUID) ([]GetCollegesForApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getCollegesForApplications, applicationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollegesForApplicationsRow{}
	for rows.Next() {
		var i GetCollegesForApplicationsRow
		if err := rows.Scan(&i.ApplicationID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentApplication = `-- name: GetStudentApplication :one
SELECT id, student_id, application_type_id, application_status_id, application_number, application_name, last_date, applied_date, submitted_date, portal_username, portal_password, remarks, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, form_type_id, branch_id FROM student_applications WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStudentApplication(ctx context.Context, id uuid.UUID) (StudentApplication, error) {
	row := q.db.QueryRow(ctx, getStudentApplication, id)
	var i StudentApplication
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ApplicationTypeID,
		&i.ApplicationStatusID,
		&i.ApplicationNumber,
		&i.ApplicationName,
		&i.LastDate,
		&i.AppliedDate,
		&i.SubmittedDate,
		&i.PortalUsername,
		&i.PortalPassword,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.FormTypeID,
		&i.BranchID,
	)
	return i, err
}

const listStudentApplications = `-- name: ListStudentApplications :many
SELECT a.id, a.student_id, a.application_type_id, a.application_status_id, a.application_number, a.application_name, a.last_date, a.applied_date, a.submitted_date, a.portal_username, a.portal_password, a.remarks, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at, a.deleted_by, a.form_type_id, a.branch_id FROM student_applications a
WHERE a.deleted_at IS NULL
  AND a.branch_id = $1
  AND ($2::text = ''
       OR a.application_name ILIKE '%'||$2||'%'
       OR a.application_number ILIKE '%'||$2||'%'
       OR EXISTS (
           SELECT 1 FROM student_application_colleges sac 
           JOIN colleges c ON sac.college_id = c.id
           WHERE sac.application_id = a.id AND c.name ILIKE '%'||$2||'%'
       ))
ORDER BY a.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentApplicationsParams struct {
	BranchID uuid.UUID
	Filter   string
	Off      int32
	Lim      int32
}

func (q *Queries) ListStudentApplications(ctx context.Context, arg ListStudentApplicationsParams) ([]StudentApplication, error) {
	rows, err := q.db.Query(ctx, listStudentApplications,
		arg.BranchID,
		arg.Filter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentApplication{}
	for rows.Next() {
		var i StudentApplication
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.ApplicationTypeID,
			&i.ApplicationStatusID,
			&i.ApplicationNumber,
			&i.ApplicationName,
			&i.LastDate,
			&i.AppliedDate,
			&i.SubmittedDate,
			&i.PortalUsername,
			&i.PortalPassword,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.FormTypeID,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextAppSequence = `-- name: NextAppSequence :one
SELECT nextval('app_seq')::bigint AS seq
`

func (q *Queries) NextAppSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextAppSequence)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const softDeleteStudentApplication = `-- name: SoftDeleteStudentApplication :execrows
UPDATE student_applications SET deleted_at = now(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteStudentApplicationParams struct {
	DeletedBy *int64
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteStudentApplication(ctx context.Context, arg SoftDeleteStudentApplicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteStudentApplication, arg.DeletedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStudentApplication = `-- name: UpdateStudentApplication :one
UPDATE student_applications SET
    application_type_id = $1,
    application_status_id = $2,
    application_number = $3,
    application_name = $4,
    last_date = $5,
    applied_date = $6,
    submitted_date = $7,
    form_type_id = $8,
    portal_username = $9,
    portal_password = $10,
    remarks = $11,
    updated_by = $12,
    updated_at = now()
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, student_id, application_type_id, application_status_id, application_number, application_name, last_date, applied_date, submitted_date, portal_username, portal_password, remarks, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, form_type_id, branch_id
`

type UpdateStudentApplicationParams struct {
	ApplicationTypeID   uuid.UUID
	ApplicationStatusID uuid.UUID
	ApplicationNumber   *string
	ApplicationName     *string
	LastDate            *time.Time
	AppliedDate         *time.Time
	SubmittedDate       *time.Time
	FormTypeID          *uuid.UUID
	PortalUsername      *string
	PortalPassword      *string
	Remarks             *string
	UpdatedBy           *int64
	ID                  uuid.UUID
}

func (q *Queries) UpdateStudentApplication(ctx context.Context, arg UpdateStudentApplicationParams) (StudentApplication, error) {
	row := q.db.QueryRow(ctx, updateStudentApplication,
		arg.ApplicationTypeID,
		arg.ApplicationStatusID,
		arg.ApplicationNumber,
		arg.ApplicationName,
		arg.LastDate,
		arg.AppliedDate,
		arg.SubmittedDate,
		arg.FormTypeID,
		arg.PortalUsername,
		arg.PortalPassword,
		arg.Remarks,
		arg.UpdatedBy,
		arg.ID,
	)
	var i StudentApplication
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ApplicationTypeID,
		&i.ApplicationStatusID,
		&i.ApplicationNumber,
		&i.ApplicationName,
		&i.LastDate,
		&i.AppliedDate,
		&i.SubmittedDate,
		&i.PortalUsername,
		&i.PortalPassword,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.FormTypeID,
		&i.BranchID,
	)
	return i, err
}
