// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: application_fee_collections.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApplicationFeeCollection = `-- name: CreateApplicationFeeCollection :one
INSERT INTO application_fee_collections (
    application_id, staff_id, college_fee_amount, payment_to_college_method, student_reimbursement_method, student_transaction_ref, staff_remarks, admin_verification_status, admin_remarks, branch_id, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, application_id, staff_id, college_fee_amount, payment_to_college_method, student_reimbursement_method, student_transaction_ref, admin_verification_status, admin_remarks, branch_id, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, staff_remarks, verified_by, verified_at
`

type CreateApplicationFeeCollectionParams struct {
	ApplicationID              uuid.UUID
	StaffID                    int64
	CollegeFeeAmount           pgtype.Numeric
	PaymentToCollegeMethod     string
	StudentReimbursementMethod string
	StudentTransactionRef      *string
	StaffRemarks               *string
	AdminVerificationStatus    string
	AdminRemarks               *string
	BranchID                   uuid.UUID
	CreatedBy                  *int64
	UpdatedBy                  *int64
}

func (q *Queries) CreateApplicationFeeCollection(ctx context.Context, arg CreateApplicationFeeCollectionParams) (ApplicationFeeCollection, error) {
	row := q.db.QueryRow(ctx, createApplicationFeeCollection,
		arg.ApplicationID,
		arg.StaffID,
		arg.CollegeFeeAmount,
		arg.PaymentToCollegeMethod,
		arg.StudentReimbursementMethod,
		arg.StudentTransactionRef,
		arg.StaffRemarks,
		arg.AdminVerificationStatus,
		arg.AdminRemarks,
		arg.BranchID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ApplicationFeeCollection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.StaffID,
		&i.CollegeFeeAmount,
		&i.PaymentToCollegeMethod,
		&i.StudentReimbursementMethod,
		&i.StudentTransactionRef,
		&i.AdminVerificationStatus,
		&i.AdminRemarks,
		&i.BranchID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.StaffRemarks,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteApplicationFeeCollection = `-- name: DeleteApplicationFeeCollection :exec
UPDATE application_fee_collections SET deleted_at = NOW(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type DeleteApplicationFeeCollectionParams struct {
	DeletedBy *int64
	ID        uuid.UUID
}

func (q *Queries) DeleteApplicationFeeCollection(ctx context.Context, arg DeleteApplicationFeeCollectionParams) error {
	_, err := q.db.Exec(ctx, deleteApplicationFeeCollection, arg.DeletedBy, arg.ID)
	return err
}

const getApplicationFeeCollection = `-- name: GetApplicationFeeCollection :one
SELECT id, application_id, staff_id, college_fee_amount, payment_to_college_method, student_reimbursement_method, student_transaction_ref, admin_verification_status, admin_remarks, branch_id, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, staff_remarks, verified_by, verified_at FROM application_fee_collections
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetApplicationFeeCollection(ctx context.Context, id uuid.UUID) (ApplicationFeeCollection, error) {
	row := q.db.QueryRow(ctx, getApplicationFeeCollection, id)
	var i ApplicationFeeCollection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.StaffID,
		&i.CollegeFeeAmount,
		&i.PaymentToCollegeMethod,
		&i.StudentReimbursementMethod,
		&i.StudentTransactionRef,
		&i.AdminVerificationStatus,
		&i.AdminRemarks,
		&i.BranchID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.StaffRemarks,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}

const listApplicationFeeCollections = `-- name: ListApplicationFeeCollections :many
SELECT c.id, c.application_id, c.staff_id, c.college_fee_amount, c.payment_to_college_method, c.student_reimbursement_method, c.student_transaction_ref, c.admin_verification_status, c.admin_remarks, c.branch_id, c.created_by, c.updated_by, c.created_at, c.updated_at, c.deleted_at, c.deleted_by, c.staff_remarks, c.verified_by, c.verified_at, 
       a.application_name, a.student_id,
       up.first_name AS staff_first_name, up.last_name AS staff_last_name,
       s.full_name AS student_first_name, NULL::text AS student_last_name,
       u.email AS staff_email,
       s.email AS student_email,
       vu.first_name AS verified_by_first_name, vu.last_name AS verified_by_last_name
FROM application_fee_collections c
JOIN student_applications a ON a.id = c.application_id
LEFT JOIN public.users u ON u.id = c.staff_id
LEFT JOIN public.user_profiles up ON up.user_id = u.id
LEFT JOIN public.user_profiles vu ON vu.user_id = c.verified_by
LEFT JOIN students s ON s.id = a.student_id
WHERE c.branch_id = $1
AND c.deleted_at IS NULL
AND ($2::bigint IS NULL OR c.staff_id = $2)
AND ($3::text IS NULL OR c.admin_verification_status = $3)
AND ($4::timestamptz IS NULL OR c.created_at >= $4)
AND ($5::timestamptz IS NULL OR c.created_at <= $5)
ORDER BY c.created_at DESC
`

type ListApplicationFeeCollectionsParams struct {
	BranchID  uuid.UUID
	StaffID   *int64
	Status    *string
	StartDate *time.Time
	EndDate   *time.Time
}

type ListApplicationFeeCollectionsRow struct {
	ID                         uuid.UUID
	ApplicationID              uuid.UUID
	StaffID                    int64
	CollegeFeeAmount           pgtype.Numeric
	PaymentToCollegeMethod     string
	StudentReimbursementMethod string
	StudentTransactionRef      *string
	AdminVerificationStatus    string
	AdminRemarks               *string
	BranchID                   uuid.UUID
	CreatedBy                  *int64
	UpdatedBy                  *int64
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	DeletedAt                  *time.Time
	DeletedBy                  *int64
	StaffRemarks               *string
	VerifiedBy                 *int64
	VerifiedAt                 *time.Time
	ApplicationName            *string
	StudentID                  uuid.UUID
	StaffFirstName             *string
	StaffLastName              *string
	StudentFirstName           *string
	StudentLastName            *string
	StaffEmail                 *string
	StudentEmail               *string
	VerifiedByFirstName        *string
	VerifiedByLastName         *string
}

func (q *Queries) ListApplicationFeeCollections(ctx context.Context, arg ListApplicationFeeCollectionsParams) ([]ListApplicationFeeCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationFeeCollections,
		arg.BranchID,
		arg.StaffID,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationFeeCollectionsRow{}
	for rows.Next() {
		var i ListApplicationFeeCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.StaffID,
			&i.CollegeFeeAmount,
			&i.PaymentToCollegeMethod,
			&i.StudentReimbursementMethod,
			&i.StudentTransactionRef,
			&i.AdminVerificationStatus,
			&i.AdminRemarks,
			&i.BranchID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.StaffRemarks,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.ApplicationName,
			&i.StudentID,
			&i.StaffFirstName,
			&i.StaffLastName,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StaffEmail,
			&i.StudentEmail,
			&i.VerifiedByFirstName,
			&i.VerifiedByLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationFeeCollection = `-- name: UpdateApplicationFeeCollection :one
UPDATE application_fee_collections SET
    college_fee_amount = COALESCE($1, college_fee_amount),
    payment_to_college_method = COALESCE($2, payment_to_college_method),
    student_reimbursement_method = COALESCE($3, student_reimbursement_method),
    student_transaction_ref = COALESCE($4, student_transaction_ref),
    staff_remarks = COALESCE($5, staff_remarks),
    admin_verification_status = COALESCE($6, admin_verification_status),
    admin_remarks = COALESCE($7, admin_remarks),
    verified_by = COALESCE($8, verified_by),
    verified_at = COALESCE($9, verified_at),
    updated_by = $10,
    updated_at = NOW()
WHERE id = $11 AND deleted_at IS NULL
RETURNING id, application_id, staff_id, college_fee_amount, payment_to_college_method, student_reimbursement_method, student_transaction_ref, admin_verification_status, admin_remarks, branch_id, created_by, updated_by, created_at, updated_at, deleted_at, deleted_by, staff_remarks, verified_by, verified_at
`

type UpdateApplicationFeeCollectionParams struct {
	CollegeFeeAmount           pgtype.Numeric
	PaymentToCollegeMethod     *string
	StudentReimbursementMethod *string
	StudentTransactionRef      *string
	StaffRemarks               *string
	AdminVerificationStatus    *string
	AdminRemarks               *string
	VerifiedBy                 *int64
	VerifiedAt                 *time.Time
	UpdatedBy                  *int64
	ID                         uuid.UUID
}

func (q *Queries) UpdateApplicationFeeCollection(ctx context.Context, arg UpdateApplicationFeeCollectionParams) (ApplicationFeeCollection, error) {
	row := q.db.QueryRow(ctx, updateApplicationFeeCollection,
		arg.CollegeFeeAmount,
		arg.PaymentToCollegeMethod,
		arg.StudentReimbursementMethod,
		arg.StudentTransactionRef,
		arg.StaffRemarks,
		arg.AdminVerificationStatus,
		arg.AdminRemarks,
		arg.VerifiedBy,
		arg.VerifiedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i ApplicationFeeCollection
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.StaffID,
		&i.CollegeFeeAmount,
		&i.PaymentToCollegeMethod,
		&i.StudentReimbursementMethod,
		&i.StudentTransactionRef,
		&i.AdminVerificationStatus,
		&i.AdminRemarks,
		&i.BranchID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.StaffRemarks,
		&i.VerifiedBy,
		&i.VerifiedAt,
	)
	return i, err
}
