// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appstatuses.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const checkApplicationStatusInUse = `-- name: CheckApplicationStatusInUse :one
SELECT EXISTS (
  SELECT 1 FROM student_applications 
  WHERE application_status_id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckApplicationStatusInUse(ctx context.Context, applicationStatusID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkApplicationStatusInUse, applicationStatusID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countApplicationStatuses = `-- name: CountApplicationStatuses :one
SELECT count(*) FROM application_statuses
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
`

func (q *Queries) CountApplicationStatuses(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationStatuses, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplicationStatus = `-- name: CreateApplicationStatus :one
INSERT INTO application_statuses (name, description, color_code, status, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, color_code, status, display_order, created_at, updated_at
`

type CreateApplicationStatusParams struct {
	Name         string
	Description  *string
	ColorCode    *string
	Status       string
	DisplayOrder int32
}

func (q *Queries) CreateApplicationStatus(ctx context.Context, arg CreateApplicationStatusParams) (ApplicationStatus, error) {
	row := q.db.QueryRow(ctx, createApplicationStatus,
		arg.Name,
		arg.Description,
		arg.ColorCode,
		arg.Status,
		arg.DisplayOrder,
	)
	var i ApplicationStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationStatus = `-- name: DeleteApplicationStatus :execrows
DELETE FROM application_statuses WHERE id = $1
`

func (q *Queries) DeleteApplicationStatus(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationStatus, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplicationStatus = `-- name: GetApplicationStatus :one
SELECT id, name, description, color_code, status, display_order, created_at, updated_at FROM application_statuses WHERE id = $1
`

func (q *Queries) GetApplicationStatus(ctx context.Context, id uuid.UUID) (ApplicationStatus, error) {
	row := q.db.QueryRow(ctx, getApplicationStatus, id)
	var i ApplicationStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationStatuses = `-- name: ListApplicationStatuses :many
SELECT id, name, description, color_code, status, display_order, created_at, updated_at FROM application_statuses
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
ORDER BY display_order ASC, name ASC
LIMIT $3 OFFSET $2
`

type ListApplicationStatusesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListApplicationStatuses(ctx context.Context, arg ListApplicationStatusesParams) ([]ApplicationStatus, error) {
	rows, err := q.db.Query(ctx, listApplicationStatuses, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationStatus{}
	for rows.Next() {
		var i ApplicationStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ColorCode,
			&i.Status,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :one
UPDATE application_statuses
SET name = $1,
    description = $2,
    color_code = $3,
    status = $4,
    display_order = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, name, description, color_code, status, display_order, created_at, updated_at
`

type UpdateApplicationStatusParams struct {
	Name         string
	Description  *string
	ColorCode    *string
	Status       string
	DisplayOrder int32
	ID           uuid.UUID
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) (ApplicationStatus, error) {
	row := q.db.QueryRow(ctx, updateApplicationStatus,
		arg.Name,
		arg.Description,
		arg.ColorCode,
		arg.Status,
		arg.DisplayOrder,
		arg.ID,
	)
	var i ApplicationStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ColorCode,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
