// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apptypes.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const checkApplicationTypeInUse = `-- name: CheckApplicationTypeInUse :one
SELECT EXISTS (
  SELECT 1 FROM student_applications 
  WHERE application_type_id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckApplicationTypeInUse(ctx context.Context, applicationTypeID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkApplicationTypeInUse, applicationTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countApplicationTypes = `-- name: CountApplicationTypes :one
SELECT count(*) FROM application_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
`

func (q *Queries) CountApplicationTypes(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationTypes, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplicationType = `-- name: CreateApplicationType :one
INSERT INTO application_types (name, description, status)
VALUES ($1, $2, $3)
RETURNING id, name, description, status, created_at, updated_at
`

type CreateApplicationTypeParams struct {
	Name        string
	Description *string
	Status      string
}

func (q *Queries) CreateApplicationType(ctx context.Context, arg CreateApplicationTypeParams) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, createApplicationType, arg.Name, arg.Description, arg.Status)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplicationType = `-- name: DeleteApplicationType :execrows
DELETE FROM application_types WHERE id = $1
`

func (q *Queries) DeleteApplicationType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApplicationType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApplicationType = `-- name: GetApplicationType :one
SELECT id, name, description, status, created_at, updated_at FROM application_types WHERE id = $1
`

func (q *Queries) GetApplicationType(ctx context.Context, id uuid.UUID) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, getApplicationType, id)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationTypes = `-- name: ListApplicationTypes :many
SELECT id, name, description, status, created_at, updated_at FROM application_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListApplicationTypesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListApplicationTypes(ctx context.Context, arg ListApplicationTypesParams) ([]ApplicationType, error) {
	rows, err := q.db.Query(ctx, listApplicationTypes, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationType{}
	for rows.Next() {
		var i ApplicationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplicationType = `-- name: UpdateApplicationType :one
UPDATE application_types
SET name = $1, description = $2, status = $3, updated_at = now()
WHERE id = $4
RETURNING id, name, description, status, created_at, updated_at
`

type UpdateApplicationTypeParams struct {
	Name        string
	Description *string
	Status      string
	ID          uuid.UUID
}

func (q *Queries) UpdateApplicationType(ctx context.Context, arg UpdateApplicationTypeParams) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, updateApplicationType,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
