// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const assignUserToBranch = `-- name: AssignUserToBranch :exec
INSERT INTO user_branches (user_id, branch_id)
VALUES ($1, $2)
ON CONFLICT (user_id, branch_id) DO NOTHING
`

type AssignUserToBranchParams struct {
	UserID   int64
	BranchID uuid.UUID
}

func (q *Queries) AssignUserToBranch(ctx context.Context, arg AssignUserToBranchParams) error {
	_, err := q.db.Exec(ctx, assignUserToBranch, arg.UserID, arg.BranchID)
	return err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
    name, code, address, contact, status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, code, address, contact, status, created_at, updated_at, deleted_at
`

type CreateBranchParams struct {
	Name    string
	Code    *string
	Address *string
	Contact *string
	Status  string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.Contact,
		arg.Status,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.Contact,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
UPDATE branches
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteBranch(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name, code, address, contact, status, created_at, updated_at, deleted_at FROM branches WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBranch(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.Contact,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserBranches = `-- name: GetUserBranches :many
SELECT b.id, b.name, b.code, b.address, b.contact, b.status, b.created_at, b.updated_at, b.deleted_at FROM branches b
JOIN user_branches ub ON b.id = ub.branch_id
WHERE ub.user_id = $1 AND b.deleted_at IS NULL
ORDER BY b.name
`

func (q *Queries) GetUserBranches(ctx context.Context, userID int64) ([]Branch, error) {
	rows, err := q.db.Query(ctx, getUserBranches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.Contact,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranches = `-- name: ListBranches :many
SELECT id, name, code, address, contact, status, created_at, updated_at, deleted_at FROM branches WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListBranches(ctx context.Context) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.Contact,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromBranch = `-- name: RemoveUserFromBranch :exec
DELETE FROM user_branches WHERE user_id = $1 AND branch_id = $2
`

type RemoveUserFromBranchParams struct {
	UserID   int64
	BranchID uuid.UUID
}

func (q *Queries) RemoveUserFromBranch(ctx context.Context, arg RemoveUserFromBranchParams) error {
	_, err := q.db.Exec(ctx, removeUserFromBranch, arg.UserID, arg.BranchID)
	return err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET
    name = $2,
    code = $3,
    address = $4,
    contact = $5,
    status = $6,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, code, address, contact, status, created_at, updated_at, deleted_at
`

type UpdateBranchParams struct {
	ID      uuid.UUID
	Name    string
	Code    *string
	Address *string
	Contact *string
	Status  string
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.Contact,
		arg.Status,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.Contact,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
