// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: castes.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const countCastes = `-- name: CountCastes :one
SELECT count(*) FROM student_castes
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
`

func (q *Queries) CountCastes(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countCastes, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCaste = `-- name: CreateCaste :one
INSERT INTO student_castes (
    name, description, status
) VALUES (
    $1, $2, $3
)
RETURNING id, name, description, status, created_at, updated_at
`

type CreateCasteParams struct {
	Name        string
	Description *string
	Status      string
}

func (q *Queries) CreateCaste(ctx context.Context, arg CreateCasteParams) (StudentCaste, error) {
	row := q.db.QueryRow(ctx, createCaste, arg.Name, arg.Description, arg.Status)
	var i StudentCaste
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCaste = `-- name: DeleteCaste :execrows
DELETE FROM student_castes WHERE id = $1
`

func (q *Queries) DeleteCaste(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCaste, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaste = `-- name: GetCaste :one
SELECT id, name, description, status, created_at, updated_at FROM student_castes WHERE id = $1
`

func (q *Queries) GetCaste(ctx context.Context, id uuid.UUID) (StudentCaste, error) {
	row := q.db.QueryRow(ctx, getCaste, id)
	var i StudentCaste
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCastes = `-- name: ListCastes :many
SELECT id, name, description, status, created_at, updated_at FROM student_castes
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListCastesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListCastes(ctx context.Context, arg ListCastesParams) ([]StudentCaste, error) {
	rows, err := q.db.Query(ctx, listCastes, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCaste{}
	for rows.Next() {
		var i StudentCaste
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCaste = `-- name: UpdateCaste :one
UPDATE student_castes SET
    name = $2,
    description = $3,
    status = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, status, created_at, updated_at
`

type UpdateCasteParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Status      string
}

func (q *Queries) UpdateCaste(ctx context.Context, arg UpdateCasteParams) (StudentCaste, error) {
	row := q.db.QueryRow(ctx, updateCaste,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i StudentCaste
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
