// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const countStudentCategories = `-- name: CountStudentCategories :one
SELECT count(*) FROM student_categories
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
`

func (q *Queries) CountStudentCategories(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentCategories, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentCategory = `-- name: CreateStudentCategory :one
INSERT INTO student_categories (name, description, status)
VALUES ($1, $2, $3)
RETURNING id, name, description, status, created_at, updated_at
`

type CreateStudentCategoryParams struct {
	Name        string
	Description *string
	Status      string
}

func (q *Queries) CreateStudentCategory(ctx context.Context, arg CreateStudentCategoryParams) (StudentCategory, error) {
	row := q.db.QueryRow(ctx, createStudentCategory, arg.Name, arg.Description, arg.Status)
	var i StudentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudentCategory = `-- name: DeleteStudentCategory :execrows
DELETE FROM student_categories WHERE id = $1
`

func (q *Queries) DeleteStudentCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudentCategory = `-- name: GetStudentCategory :one
SELECT id, name, description, status, created_at, updated_at FROM student_categories WHERE id = $1
`

func (q *Queries) GetStudentCategory(ctx context.Context, id uuid.UUID) (StudentCategory, error) {
	row := q.db.QueryRow(ctx, getStudentCategory, id)
	var i StudentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentCategories = `-- name: ListStudentCategories :many
SELECT id, name, description, status, created_at, updated_at FROM student_categories
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListStudentCategoriesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListStudentCategories(ctx context.Context, arg ListStudentCategoriesParams) ([]StudentCategory, error) {
	rows, err := q.db.Query(ctx, listStudentCategories, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCategory{}
	for rows.Next() {
		var i StudentCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentCategory = `-- name: UpdateStudentCategory :one
UPDATE student_categories
SET name = $1,
    description = $2,
    status = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, name, description, status, created_at, updated_at
`

type UpdateStudentCategoryParams struct {
	Name        string
	Description *string
	Status      string
	ID          uuid.UUID
}

func (q *Queries) UpdateStudentCategory(ctx context.Context, arg UpdateStudentCategoryParams) (StudentCategory, error) {
	row := q.db.QueryRow(ctx, updateStudentCategory,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i StudentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
