// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: colleges.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const createCollege = `-- name: CreateCollege :one
INSERT INTO colleges (tenant_id, name, created_by, updated_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, created_at, updated_at, deleted_at, created_by, updated_by
`

type CreateCollegeParams struct {
	TenantID  int64
	Name      string
	CreatedBy *int64
	UpdatedBy *int64
}

func (q *Queries) CreateCollege(ctx context.Context, arg CreateCollegeParams) (College, error) {
	row := q.db.QueryRow(ctx, createCollege,
		arg.TenantID,
		arg.Name,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i College
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getCollege = `-- name: GetCollege :one
SELECT id, tenant_id, name, created_at, updated_at, deleted_at, created_by, updated_by FROM colleges WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCollege(ctx context.Context, id uuid.UUID) (College, error) {
	row := q.db.QueryRow(ctx, getCollege, id)
	var i College
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listColleges = `-- name: ListColleges :many
SELECT id, tenant_id, name, created_at, updated_at, deleted_at, created_by, updated_by FROM colleges
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListColleges(ctx context.Context) ([]College, error) {
	rows, err := q.db.Query(ctx, listColleges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []College{}
	for rows.Next() {
		var i College
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCollege = `-- name: SoftDeleteCollege :execrows
UPDATE colleges SET deleted_at = now(), updated_by = $2 WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteCollegeParams struct {
	ID        uuid.UUID
	UpdatedBy *int64
}

func (q *Queries) SoftDeleteCollege(ctx context.Context, arg SoftDeleteCollegeParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCollege, arg.ID, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCollege = `-- name: UpdateCollege :one
UPDATE colleges SET
    name = $2,
    updated_by = $3,
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, name, created_at, updated_at, deleted_at, created_by, updated_by
`

type UpdateCollegeParams struct {
	ID        uuid.UUID
	Name      string
	UpdatedBy *int64
}

func (q *Queries) UpdateCollege(ctx context.Context, arg UpdateCollegeParams) (College, error) {
	row := q.db.QueryRow(ctx, updateCollege, arg.ID, arg.Name, arg.UpdatedBy)
	var i College
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
