// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActionCenterItems = `-- name: GetActionCenterItems :many
SELECT a.id, s.student_code, s.full_name AS student_name, 
       'Application missing portal credentials'::text AS issue, 'High'::text AS priority
FROM student_applications a
JOIN students s ON a.student_id = s.id
WHERE a.deleted_at IS NULL AND a.branch_id = $1 AND a.branch_id = $1 AND s.deleted_at IS NULL AND s.branch_id = $1 AND s.branch_id = $1 
  AND (a.portal_username = '' OR a.portal_username IS NULL)
  AND a.created_at >= $2 AND a.created_at <= $3
LIMIT 10
`

type GetActionCenterItemsParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type GetActionCenterItemsRow struct {
	ID          uuid.UUID
	StudentCode string
	StudentName string
	Issue       string
	Priority    string
}

func (q *Queries) GetActionCenterItems(ctx context.Context, arg GetActionCenterItemsParams) ([]GetActionCenterItemsRow, error) {
	rows, err := q.db.Query(ctx, getActionCenterItems, arg.BranchID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActionCenterItemsRow{}
	for rows.Next() {
		var i GetActionCenterItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.StudentName,
			&i.Issue,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdmissionTrend = `-- name: GetAdmissionTrend :many
WITH months AS (
    SELECT generate_series(
        date_trunc('month', $1::timestamp),
        date_trunc('month', $2::timestamp),
        '1 month'::interval
    ) AS month_date
)
SELECT 
    to_char(m.month_date, 'Mon YYYY') AS month,
    count(s.id) AS count
FROM months m
LEFT JOIN students s ON date_trunc('month', s.created_at) = m.month_date 
    AND s.created_at >= $1 
    AND s.created_at <= $2
    AND s.deleted_at IS NULL AND s.branch_id = $3 AND s.branch_id = $3
GROUP BY m.month_date
ORDER BY m.month_date
`

type GetAdmissionTrendParams struct {
	StartDate time.Time
	EndDate   time.Time
	BranchID  uuid.UUID
}

type GetAdmissionTrendRow struct {
	Month string
	Count int64
}

func (q *Queries) GetAdmissionTrend(ctx context.Context, arg GetAdmissionTrendParams) ([]GetAdmissionTrendRow, error) {
	rows, err := q.db.Query(ctx, getAdmissionTrend, arg.StartDate, arg.EndDate, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAdmissionTrendRow{}
	for rows.Next() {
		var i GetAdmissionTrendRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationStatusDistribution = `-- name: GetApplicationStatusDistribution :many
SELECT s.name AS status_name, count(a.id) AS count
FROM application_statuses s
LEFT JOIN student_applications a ON a.application_status_id = s.id AND a.deleted_at IS NULL AND a.branch_id = $1 AND a.branch_id = $1 AND a.created_at >= $2 AND a.created_at <= $3
GROUP BY s.name
ORDER BY count DESC
`

type GetApplicationStatusDistributionParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type GetApplicationStatusDistributionRow struct {
	StatusName string
	Count      int64
}

func (q *Queries) GetApplicationStatusDistribution(ctx context.Context, arg GetApplicationStatusDistributionParams) ([]GetApplicationStatusDistributionRow, error) {
	rows, err := q.db.Query(ctx, getApplicationStatusDistribution, arg.BranchID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApplicationStatusDistributionRow{}
	for rows.Next() {
		var i GetApplicationStatusDistributionRow
		if err := rows.Scan(&i.StatusName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationTypesDistribution = `-- name: GetApplicationTypesDistribution :many
SELECT t.name AS type_name, count(a.id) AS count
FROM application_types t
LEFT JOIN student_applications a ON a.application_type_id = t.id AND a.deleted_at IS NULL AND a.branch_id = $1 AND a.branch_id = $1 AND a.created_at >= $2 AND a.created_at <= $3
GROUP BY t.name
ORDER BY count DESC
`

type GetApplicationTypesDistributionParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type GetApplicationTypesDistributionRow struct {
	TypeName string
	Count    int64
}

func (q *Queries) GetApplicationTypesDistribution(ctx context.Context, arg GetApplicationTypesDistributionParams) ([]GetApplicationTypesDistributionRow, error) {
	rows, err := q.db.Query(ctx, getApplicationTypesDistribution, arg.BranchID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApplicationTypesDistributionRow{}
	for rows.Next() {
		var i GetApplicationTypesDistributionRow
		if err := rows.Scan(&i.TypeName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentMethodDistribution = `-- name: GetPaymentMethodDistribution :many
SELECT payment_method AS method, COALESCE(sum(amount), 0)::numeric AS amount
FROM student_payments
WHERE branch_id = $1 AND payment_date >= $2 AND payment_date <= $3
GROUP BY payment_method
ORDER BY amount DESC
`

type GetPaymentMethodDistributionParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type GetPaymentMethodDistributionRow struct {
	Method *string
	Amount pgtype.Numeric
}

func (q *Queries) GetPaymentMethodDistribution(ctx context.Context, arg GetPaymentMethodDistributionParams) ([]GetPaymentMethodDistributionRow, error) {
	rows, err := q.db.Query(ctx, getPaymentMethodDistribution, arg.BranchID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentMethodDistributionRow{}
	for rows.Next() {
		var i GetPaymentMethodDistributionRow
		if err := rows.Scan(&i.Method, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingApplications = `-- name: GetPendingApplications :one
SELECT count(*) FROM student_applications a 
JOIN application_statuses s ON a.application_status_id = s.id 
WHERE a.deleted_at IS NULL AND a.branch_id = $1 AND a.branch_id = $1 AND s.name ILIKE '%pending%' AND a.created_at >= $2 AND a.created_at <= $3
`

type GetPendingApplicationsParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetPendingApplications(ctx context.Context, arg GetPendingApplicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPendingApplications, arg.BranchID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRevenueCollectionTrend = `-- name: GetRevenueCollectionTrend :many
WITH months AS (
    SELECT generate_series(
        date_trunc('month', $1::timestamp),
        date_trunc('month', $2::timestamp),
        '1 month'::interval
    ) AS month_date
)
SELECT 
    to_char(m.month_date, 'Mon YYYY') AS month,
    COALESCE(sum(p.amount), 0)::numeric AS amount
FROM months m
LEFT JOIN student_payments p ON date_trunc('month', p.payment_date) = m.month_date 
    AND p.payment_date >= $1 
    AND p.payment_date <= $2
    AND p.branch_id = $3
GROUP BY m.month_date
ORDER BY m.month_date
`

type GetRevenueCollectionTrendParams struct {
	StartDate time.Time
	EndDate   time.Time
	BranchID  uuid.UUID
}

type GetRevenueCollectionTrendRow struct {
	Month  string
	Amount pgtype.Numeric
}

func (q *Queries) GetRevenueCollectionTrend(ctx context.Context, arg GetRevenueCollectionTrendParams) ([]GetRevenueCollectionTrendRow, error) {
	rows, err := q.db.Query(ctx, getRevenueCollectionTrend, arg.StartDate, arg.EndDate, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueCollectionTrendRow{}
	for rows.Next() {
		var i GetRevenueCollectionTrendRow
		if err := rows.Scan(&i.Month, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentDistributionByCategory = `-- name: GetStudentDistributionByCategory :many
SELECT c.name AS category_name, count(s.id) AS count
FROM student_categories c
LEFT JOIN students s ON s.category_id = c.id AND s.deleted_at IS NULL AND s.branch_id = $1 AND s.branch_id = $1 AND s.created_at >= $2 AND s.created_at <= $3
GROUP BY c.name
ORDER BY count DESC
`

type GetStudentDistributionByCategoryParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

type GetStudentDistributionByCategoryRow struct {
	CategoryName string
	Count        int64
}

func (q *Queries) GetStudentDistributionByCategory(ctx context.Context, arg GetStudentDistributionByCategoryParams) ([]GetStudentDistributionByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStudentDistributionByCategory, arg.BranchID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentDistributionByCategoryRow{}
	for rows.Next() {
		var i GetStudentDistributionByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalApplications = `-- name: GetTotalApplications :one
SELECT count(*) FROM student_applications WHERE deleted_at IS NULL AND branch_id = $1 AND branch_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetTotalApplicationsParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTotalApplications(ctx context.Context, arg GetTotalApplicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalApplications, arg.BranchID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalFeeCollected = `-- name: GetTotalFeeCollected :one
SELECT COALESCE(sum(amount), 0)::numeric FROM student_payments WHERE branch_id = $1 AND payment_date >= $2 AND payment_date <= $3
`

type GetTotalFeeCollectedParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTotalFeeCollected(ctx context.Context, arg GetTotalFeeCollectedParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalFeeCollected, arg.BranchID, arg.StartDate, arg.EndDate)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalFeeDiscount = `-- name: GetTotalFeeDiscount :one
SELECT COALESCE(sum(discount_amount), 0)::numeric FROM student_fee_plans WHERE branch_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetTotalFeeDiscountParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTotalFeeDiscount(ctx context.Context, arg GetTotalFeeDiscountParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalFeeDiscount, arg.BranchID, arg.StartDate, arg.EndDate)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalFeePlanned = `-- name: GetTotalFeePlanned :one
SELECT COALESCE(sum(total_amount), 0)::numeric FROM student_fee_plans WHERE branch_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetTotalFeePlannedParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTotalFeePlanned(ctx context.Context, arg GetTotalFeePlannedParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalFeePlanned, arg.BranchID, arg.StartDate, arg.EndDate)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalStudents = `-- name: GetTotalStudents :one
SELECT count(*) FROM students WHERE deleted_at IS NULL AND branch_id = $1 AND branch_id = $1 AND created_at >= $2 AND created_at <= $3
`

type GetTotalStudentsParams struct {
	BranchID  uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTotalStudents(ctx context.Context, arg GetTotalStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalStudents, arg.BranchID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUpcomingDeadlines = `-- name: GetUpcomingDeadlines :many
SELECT a.id, s.student_code, s.full_name AS student_name, 
       a.application_name, a.last_date, 
       EXTRACT(DAY FROM a.last_date - now())::int AS remaining_days
FROM student_applications a
JOIN students s ON a.student_id = s.id
WHERE a.deleted_at IS NULL AND a.branch_id = $1 AND a.branch_id = $1 AND s.deleted_at IS NULL AND s.branch_id = $1 AND s.branch_id = $1 
  AND a.last_date >= now() 
  AND a.last_date <= now() + interval '30 days'
ORDER BY a.last_date ASC
LIMIT 10
`

type GetUpcomingDeadlinesRow struct {
	ID              uuid.UUID
	StudentCode     string
	StudentName     string
	ApplicationName *string
	LastDate        *time.Time
	RemainingDays   int32
}

func (q *Queries) GetUpcomingDeadlines(ctx context.Context, branchID uuid.UUID) ([]GetUpcomingDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingDeadlines, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingDeadlinesRow{}
	for rows.Next() {
		var i GetUpcomingDeadlinesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.StudentName,
			&i.ApplicationName,
			&i.LastDate,
			&i.RemainingDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
