// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dummy.sql

package tenant

import (
	"context"
)

const getTenantDummy = `-- name: GetTenantDummy :one
SELECT 1
`

func (q *Queries) GetTenantDummy(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTenantDummy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
