// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeplans.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudentFeePlans = `-- name: CountStudentFeePlans :one
SELECT count(*) FROM student_fee_plans fp
WHERE fp.branch_id = $1 AND ($2::text = '' OR fp.fee_name ILIKE '%'||$2||'%')
`

type CountStudentFeePlansParams struct {
	BranchID uuid.UUID
	Filter   string
}

func (q *Queries) CountStudentFeePlans(ctx context.Context, arg CountStudentFeePlansParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentFeePlans, arg.BranchID, arg.Filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentFeePlan = `-- name: CreateStudentFeePlan :one
INSERT INTO student_fee_plans
    (student_id, branch_id, fee_type_id, fee_name, total_amount, discount_amount, discount_reason, remarks, created_by)
VALUES
    ($1, $2, $3, $4, $5,
     $6, $7, $8, $9)
RETURNING id, student_id, fee_type_id, fee_name, total_amount, discount_amount, discount_reason, remarks, created_at, updated_at, branch_id, created_by
`

type CreateStudentFeePlanParams struct {
	StudentID      uuid.UUID
	BranchID       uuid.UUID
	FeeTypeID      *uuid.UUID
	FeeName        *string
	TotalAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	DiscountReason *string
	Remarks        *string
	CreatedBy      *int64
}

func (q *Queries) CreateStudentFeePlan(ctx context.Context, arg CreateStudentFeePlanParams) (StudentFeePlan, error) {
	row := q.db.QueryRow(ctx, createStudentFeePlan,
		arg.StudentID,
		arg.BranchID,
		arg.FeeTypeID,
		arg.FeeName,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.DiscountReason,
		arg.Remarks,
		arg.CreatedBy,
	)
	var i StudentFeePlan
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FeeTypeID,
		&i.FeeName,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
	)
	return i, err
}

const deleteStudentFeePlan = `-- name: DeleteStudentFeePlan :execrows
DELETE FROM student_fee_plans WHERE id = $1
`

func (q *Queries) DeleteStudentFeePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentFeePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFeePlansByStudent = `-- name: GetFeePlansByStudent :many
SELECT fp.id, fp.student_id, fp.fee_type_id, fp.fee_name, fp.total_amount, fp.discount_amount, fp.discount_reason, fp.remarks, fp.created_at, fp.updated_at, fp.branch_id, fp.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_fee_plans fp
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = fp.created_by
LEFT JOIN public.users u ON u.id = fp.created_by
WHERE fp.student_id = $1 AND fp.branch_id = $2
ORDER BY fp.created_at DESC
`

type GetFeePlansByStudentParams struct {
	StudentID uuid.UUID
	BranchID  uuid.UUID
}

type GetFeePlansByStudentRow struct {
	ID             uuid.UUID
	StudentID      uuid.UUID
	FeeTypeID      *uuid.UUID
	FeeName        *string
	TotalAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	DiscountReason *string
	Remarks        *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BranchID       uuid.UUID
	CreatedBy      *int64
	FeeTypeName    *string
	CreatedByName  string
}

func (q *Queries) GetFeePlansByStudent(ctx context.Context, arg GetFeePlansByStudentParams) ([]GetFeePlansByStudentRow, error) {
	rows, err := q.db.Query(ctx, getFeePlansByStudent, arg.StudentID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeePlansByStudentRow{}
	for rows.Next() {
		var i GetFeePlansByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FeeTypeID,
			&i.FeeName,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DiscountReason,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CreatedBy,
			&i.FeeTypeName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentFeePlan = `-- name: GetStudentFeePlan :one
SELECT fp.id, fp.student_id, fp.fee_type_id, fp.fee_name, fp.total_amount, fp.discount_amount, fp.discount_reason, fp.remarks, fp.created_at, fp.updated_at, fp.branch_id, fp.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_fee_plans fp
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = fp.created_by
LEFT JOIN public.users u ON u.id = fp.created_by
WHERE fp.id = $1
`

type GetStudentFeePlanRow struct {
	ID             uuid.UUID
	StudentID      uuid.UUID
	FeeTypeID      *uuid.UUID
	FeeName        *string
	TotalAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	DiscountReason *string
	Remarks        *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BranchID       uuid.UUID
	CreatedBy      *int64
	FeeTypeName    *string
	CreatedByName  string
}

func (q *Queries) GetStudentFeePlan(ctx context.Context, id uuid.UUID) (GetStudentFeePlanRow, error) {
	row := q.db.QueryRow(ctx, getStudentFeePlan, id)
	var i GetStudentFeePlanRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FeeTypeID,
		&i.FeeName,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
		&i.FeeTypeName,
		&i.CreatedByName,
	)
	return i, err
}

const listStudentFeePlans = `-- name: ListStudentFeePlans :many
SELECT fp.id, fp.student_id, fp.fee_type_id, fp.fee_name, fp.total_amount, fp.discount_amount, fp.discount_reason, fp.remarks, fp.created_at, fp.updated_at, fp.branch_id, fp.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_fee_plans fp
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = fp.created_by
LEFT JOIN public.users u ON u.id = fp.created_by
WHERE fp.branch_id = $1 AND ($2::text = '' OR fp.fee_name ILIKE '%'||$2||'%')
ORDER BY fp.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentFeePlansParams struct {
	BranchID uuid.UUID
	Filter   string
	Off      int32
	Lim      int32
}

type ListStudentFeePlansRow struct {
	ID             uuid.UUID
	StudentID      uuid.UUID
	FeeTypeID      *uuid.UUID
	FeeName        *string
	TotalAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	DiscountReason *string
	Remarks        *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	BranchID       uuid.UUID
	CreatedBy      *int64
	FeeTypeName    *string
	CreatedByName  string
}

func (q *Queries) ListStudentFeePlans(ctx context.Context, arg ListStudentFeePlansParams) ([]ListStudentFeePlansRow, error) {
	rows, err := q.db.Query(ctx, listStudentFeePlans,
		arg.BranchID,
		arg.Filter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentFeePlansRow{}
	for rows.Next() {
		var i ListStudentFeePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FeeTypeID,
			&i.FeeName,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.DiscountReason,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CreatedBy,
			&i.FeeTypeName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCollectedForFeePlan = `-- name: SumCollectedForFeePlan :one
SELECT COALESCE(sum(amount), 0)::numeric AS collected
FROM student_payments WHERE student_fee_plan_id = $1
`

func (q *Queries) SumCollectedForFeePlan(ctx context.Context, studentFeePlanID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCollectedForFeePlan, studentFeePlanID)
	var collected pgtype.Numeric
	err := row.Scan(&collected)
	return collected, err
}

const updateStudentFeePlan = `-- name: UpdateStudentFeePlan :one
UPDATE student_fee_plans SET
    fee_type_id = $1,
    fee_name = $2,
    total_amount = $3,
    discount_amount = $4,
    discount_reason = $5,
    remarks = $6,
    updated_at = now()
WHERE id = $7
RETURNING id, student_id, fee_type_id, fee_name, total_amount, discount_amount, discount_reason, remarks, created_at, updated_at, branch_id, created_by
`

type UpdateStudentFeePlanParams struct {
	FeeTypeID      *uuid.UUID
	FeeName        *string
	TotalAmount    pgtype.Numeric
	DiscountAmount pgtype.Numeric
	DiscountReason *string
	Remarks        *string
	ID             uuid.UUID
}

func (q *Queries) UpdateStudentFeePlan(ctx context.Context, arg UpdateStudentFeePlanParams) (StudentFeePlan, error) {
	row := q.db.QueryRow(ctx, updateStudentFeePlan,
		arg.FeeTypeID,
		arg.FeeName,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.DiscountReason,
		arg.Remarks,
		arg.ID,
	)
	var i StudentFeePlan
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FeeTypeID,
		&i.FeeName,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.DiscountReason,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
	)
	return i, err
}
