// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feetypes.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignCategoryToFeeType = `-- name: AssignCategoryToFeeType :exec
INSERT INTO fee_type_categories (fee_type_id, category_id) VALUES ($1, $2)
`

type AssignCategoryToFeeTypeParams struct {
	FeeTypeID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) AssignCategoryToFeeType(ctx context.Context, arg AssignCategoryToFeeTypeParams) error {
	_, err := q.db.Exec(ctx, assignCategoryToFeeType, arg.FeeTypeID, arg.CategoryID)
	return err
}

const clearCategoriesForFeeType = `-- name: ClearCategoriesForFeeType :exec
DELETE FROM fee_type_categories WHERE fee_type_id = $1
`

func (q *Queries) ClearCategoriesForFeeType(ctx context.Context, feeTypeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCategoriesForFeeType, feeTypeID)
	return err
}

const countFeeTypes = `-- name: CountFeeTypes :one
SELECT count(*) FROM fee_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
`

func (q *Queries) CountFeeTypes(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countFeeTypes, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeeType = `-- name: CreateFeeType :one
INSERT INTO fee_types (name, description, amount, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, status, created_at, updated_at, amount
`

type CreateFeeTypeParams struct {
	Name        string
	Description *string
	Amount      pgtype.Numeric
	Status      string
}

func (q *Queries) CreateFeeType(ctx context.Context, arg CreateFeeTypeParams) (FeeType, error) {
	row := q.db.QueryRow(ctx, createFeeType,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Status,
	)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
	)
	return i, err
}

const deleteFeeType = `-- name: DeleteFeeType :execrows
DELETE FROM fee_types WHERE id = $1
`

func (q *Queries) DeleteFeeType(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeeType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllFeeTypeCategories = `-- name: GetAllFeeTypeCategories :many
SELECT fee_type_id, category_id FROM fee_type_categories
`

func (q *Queries) GetAllFeeTypeCategories(ctx context.Context) ([]FeeTypeCategory, error) {
	rows, err := q.db.Query(ctx, getAllFeeTypeCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeTypeCategory{}
	for rows.Next() {
		var i FeeTypeCategory
		if err := rows.Scan(&i.FeeTypeID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesForFeeType = `-- name: GetCategoriesForFeeType :many
SELECT category_id FROM fee_type_categories WHERE fee_type_id = $1
`

func (q *Queries) GetCategoriesForFeeType(ctx context.Context, feeTypeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getCategoriesForFeeType, feeTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var category_id uuid.UUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeeType = `-- name: GetFeeType :one
SELECT id, name, description, status, created_at, updated_at, amount FROM fee_types WHERE id = $1
`

func (q *Queries) GetFeeType(ctx context.Context, id uuid.UUID) (FeeType, error) {
	row := q.db.QueryRow(ctx, getFeeType, id)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
	)
	return i, err
}

const getFeeTypeByCategory = `-- name: GetFeeTypeByCategory :one
SELECT ft.id, ft.name, ft.description, ft.status, ft.created_at, ft.updated_at, ft.amount FROM fee_types ft
JOIN fee_type_categories ftc ON ft.id = ftc.fee_type_id
WHERE ftc.category_id = $1 LIMIT 1
`

func (q *Queries) GetFeeTypeByCategory(ctx context.Context, categoryID uuid.UUID) (FeeType, error) {
	row := q.db.QueryRow(ctx, getFeeTypeByCategory, categoryID)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
	)
	return i, err
}

const listFeeTypes = `-- name: ListFeeTypes :many
SELECT id, name, description, status, created_at, updated_at, amount FROM fee_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%' OR description ILIKE '%'||$1||'%')
ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListFeeTypesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListFeeTypes(ctx context.Context, arg ListFeeTypesParams) ([]FeeType, error) {
	rows, err := q.db.Query(ctx, listFeeTypes, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeeType{}
	for rows.Next() {
		var i FeeType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeeType = `-- name: UpdateFeeType :one
UPDATE fee_types
SET name = $1, description = $2, amount = $3, status = $4, updated_at = now()
WHERE id = $5
RETURNING id, name, description, status, created_at, updated_at, amount
`

type UpdateFeeTypeParams struct {
	Name        string
	Description *string
	Amount      pgtype.Numeric
	Status      string
	ID          uuid.UUID
}

func (q *Queries) UpdateFeeType(ctx context.Context, arg UpdateFeeTypeParams) (FeeType, error) {
	row := q.db.QueryRow(ctx, updateFeeType,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.Status,
		arg.ID,
	)
	var i FeeType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Amount,
	)
	return i, err
}
