// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_types.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const countFormTypes = `-- name: CountFormTypes :one
SELECT count(*) FROM form_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
`

func (q *Queries) CountFormTypes(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countFormTypes, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFormType = `-- name: CreateFormType :one
INSERT INTO form_types (
    name, description, status, display_order
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, description, status, display_order, created_at, updated_at
`

type CreateFormTypeParams struct {
	Name         string
	Description  *string
	Status       string
	DisplayOrder int32
}

func (q *Queries) CreateFormType(ctx context.Context, arg CreateFormTypeParams) (FormType, error) {
	row := q.db.QueryRow(ctx, createFormType,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DisplayOrder,
	)
	var i FormType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFormType = `-- name: DeleteFormType :exec
DELETE FROM form_types WHERE id = $1
`

func (q *Queries) DeleteFormType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFormType, id)
	return err
}

const getFormType = `-- name: GetFormType :one
SELECT id, name, description, status, display_order, created_at, updated_at FROM form_types WHERE id = $1
`

func (q *Queries) GetFormType(ctx context.Context, id uuid.UUID) (FormType, error) {
	row := q.db.QueryRow(ctx, getFormType, id)
	var i FormType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFormTypes = `-- name: ListFormTypes :many
SELECT id, name, description, status, display_order, created_at, updated_at FROM form_types
WHERE ($1::text = '' OR name ILIKE '%'||$1||'%')
ORDER BY display_order ASC, name ASC
LIMIT $3 OFFSET $2
`

type ListFormTypesParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListFormTypes(ctx context.Context, arg ListFormTypesParams) ([]FormType, error) {
	rows, err := q.db.Query(ctx, listFormTypes, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormType{}
	for rows.Next() {
		var i FormType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormType = `-- name: UpdateFormType :one
UPDATE form_types SET
    name = $1,
    description = $2,
    status = $3,
    display_order = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, name, description, status, display_order, created_at, updated_at
`

type UpdateFormTypeParams struct {
	Name         string
	Description  *string
	Status       string
	DisplayOrder int32
	ID           uuid.UUID
}

func (q *Queries) UpdateFormType(ctx context.Context, arg UpdateFormTypeParams) (FormType, error) {
	row := q.db.QueryRow(ctx, updateFormType,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DisplayOrder,
		arg.ID,
	)
	var i FormType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
