// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStudentPayments = `-- name: CountStudentPayments :one
SELECT count(*) FROM student_payments p
WHERE p.branch_id = $1 AND ($2::text = '' OR p.payment_number ILIKE '%'||$2||'%' OR p.receipt_number ILIKE '%'||$2||'%')
`

type CountStudentPaymentsParams struct {
	BranchID uuid.UUID
	Filter   string
}

func (q *Queries) CountStudentPayments(ctx context.Context, arg CountStudentPaymentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentPayments, arg.BranchID, arg.Filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentPayment = `-- name: CreateStudentPayment :one
INSERT INTO student_payments
    (payment_number, receipt_number, student_id, branch_id, student_fee_plan_id, payment_date, amount, payment_method, reference_number, remarks, created_by)
VALUES
    ($1, $2, $3, $4, $5,
     $6, $7, $8, $9, $10, $11)
RETURNING id, payment_number, receipt_number, student_id, student_fee_plan_id, payment_date, amount, payment_method, reference_number, remarks, created_at, updated_at, branch_id, created_by
`

type CreateStudentPaymentParams struct {
	PaymentNumber    string
	ReceiptNumber    *string
	StudentID        uuid.UUID
	BranchID         uuid.UUID
	StudentFeePlanID uuid.UUID
	PaymentDate      time.Time
	Amount           pgtype.Numeric
	PaymentMethod    *string
	ReferenceNumber  *string
	Remarks          *string
	CreatedBy        *int64
}

func (q *Queries) CreateStudentPayment(ctx context.Context, arg CreateStudentPaymentParams) (StudentPayment, error) {
	row := q.db.QueryRow(ctx, createStudentPayment,
		arg.PaymentNumber,
		arg.ReceiptNumber,
		arg.StudentID,
		arg.BranchID,
		arg.StudentFeePlanID,
		arg.PaymentDate,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Remarks,
		arg.CreatedBy,
	)
	var i StudentPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.ReceiptNumber,
		&i.StudentID,
		&i.StudentFeePlanID,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
	)
	return i, err
}

const deleteStudentPayment = `-- name: DeleteStudentPayment :execrows
DELETE FROM student_payments WHERE id = $1
`

func (q *Queries) DeleteStudentPayment(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentPayment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaymentsByFeePlan = `-- name: GetPaymentsByFeePlan :many
SELECT p.id, p.payment_number, p.receipt_number, p.student_id, p.student_fee_plan_id, p.payment_date, p.amount, p.payment_method, p.reference_number, p.remarks, p.created_at, p.updated_at, p.branch_id, p.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_payments p
LEFT JOIN student_fee_plans fp ON fp.id = p.student_fee_plan_id
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = p.created_by
LEFT JOIN public.users u ON u.id = p.created_by
WHERE p.student_fee_plan_id = $1 AND p.branch_id = $2
ORDER BY p.payment_date DESC, p.created_at DESC
`

type GetPaymentsByFeePlanParams struct {
	StudentFeePlanID uuid.UUID
	BranchID         uuid.UUID
}

type GetPaymentsByFeePlanRow struct {
	ID               uuid.UUID
	PaymentNumber    string
	ReceiptNumber    *string
	StudentID        uuid.UUID
	StudentFeePlanID uuid.UUID
	PaymentDate      time.Time
	Amount           pgtype.Numeric
	PaymentMethod    *string
	ReferenceNumber  *string
	Remarks          *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	BranchID         uuid.UUID
	CreatedBy        *int64
	FeeTypeName      *string
	CreatedByName    string
}

func (q *Queries) GetPaymentsByFeePlan(ctx context.Context, arg GetPaymentsByFeePlanParams) ([]GetPaymentsByFeePlanRow, error) {
	rows, err := q.db.Query(ctx, getPaymentsByFeePlan, arg.StudentFeePlanID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentsByFeePlanRow{}
	for rows.Next() {
		var i GetPaymentsByFeePlanRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.ReceiptNumber,
			&i.StudentID,
			&i.StudentFeePlanID,
			&i.PaymentDate,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CreatedBy,
			&i.FeeTypeName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentsByStudent = `-- name: GetPaymentsByStudent :many
SELECT p.id, p.payment_number, p.receipt_number, p.student_id, p.student_fee_plan_id, p.payment_date, p.amount, p.payment_method, p.reference_number, p.remarks, p.created_at, p.updated_at, p.branch_id, p.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_payments p
LEFT JOIN student_fee_plans fp ON fp.id = p.student_fee_plan_id
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = p.created_by
LEFT JOIN public.users u ON u.id = p.created_by
WHERE p.student_id = $1 AND p.branch_id = $2
ORDER BY p.payment_date DESC, p.created_at DESC
`

type GetPaymentsByStudentParams struct {
	StudentID uuid.UUID
	BranchID  uuid.UUID
}

type GetPaymentsByStudentRow struct {
	ID               uuid.UUID
	PaymentNumber    string
	ReceiptNumber    *string
	StudentID        uuid.UUID
	StudentFeePlanID uuid.UUID
	PaymentDate      time.Time
	Amount           pgtype.Numeric
	PaymentMethod    *string
	ReferenceNumber  *string
	Remarks          *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	BranchID         uuid.UUID
	CreatedBy        *int64
	FeeTypeName      *string
	CreatedByName    string
}

func (q *Queries) GetPaymentsByStudent(ctx context.Context, arg GetPaymentsByStudentParams) ([]GetPaymentsByStudentRow, error) {
	rows, err := q.db.Query(ctx, getPaymentsByStudent, arg.StudentID, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentsByStudentRow{}
	for rows.Next() {
		var i GetPaymentsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.ReceiptNumber,
			&i.StudentID,
			&i.StudentFeePlanID,
			&i.PaymentDate,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CreatedBy,
			&i.FeeTypeName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentPayment = `-- name: GetStudentPayment :one
SELECT p.id, p.payment_number, p.receipt_number, p.student_id, p.student_fee_plan_id, p.payment_date, p.amount, p.payment_method, p.reference_number, p.remarks, p.created_at, p.updated_at, p.branch_id, p.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_payments p
LEFT JOIN student_fee_plans fp ON fp.id = p.student_fee_plan_id
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = p.created_by
LEFT JOIN public.users u ON u.id = p.created_by
WHERE p.id = $1
`

type GetStudentPaymentRow struct {
	ID               uuid.UUID
	PaymentNumber    string
	ReceiptNumber    *string
	StudentID        uuid.UUID
	StudentFeePlanID uuid.UUID
	PaymentDate      time.Time
	Amount           pgtype.Numeric
	PaymentMethod    *string
	ReferenceNumber  *string
	Remarks          *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	BranchID         uuid.UUID
	CreatedBy        *int64
	FeeTypeName      *string
	CreatedByName    string
}

func (q *Queries) GetStudentPayment(ctx context.Context, id uuid.UUID) (GetStudentPaymentRow, error) {
	row := q.db.QueryRow(ctx, getStudentPayment, id)
	var i GetStudentPaymentRow
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.ReceiptNumber,
		&i.StudentID,
		&i.StudentFeePlanID,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
		&i.FeeTypeName,
		&i.CreatedByName,
	)
	return i, err
}

const listStudentPayments = `-- name: ListStudentPayments :many
SELECT p.id, p.payment_number, p.receipt_number, p.student_id, p.student_fee_plan_id, p.payment_date, p.amount, p.payment_method, p.reference_number, p.remarks, p.created_at, p.updated_at, p.branch_id, p.created_by, ft.name AS fee_type_name,
       COALESCE(NULLIF(TRIM(CONCAT(up.first_name, ' ', up.last_name)), ''), u.email, '')::text AS created_by_name
FROM student_payments p
LEFT JOIN student_fee_plans fp ON fp.id = p.student_fee_plan_id
LEFT JOIN fee_types ft ON ft.id = fp.fee_type_id
LEFT JOIN public.user_profiles up ON up.user_id = p.created_by
LEFT JOIN public.users u ON u.id = p.created_by
WHERE p.branch_id = $1 AND ($2::text = '' OR p.payment_number ILIKE '%'||$2||'%' OR p.receipt_number ILIKE '%'||$2||'%')
ORDER BY p.payment_date DESC, p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStudentPaymentsParams struct {
	BranchID uuid.UUID
	Filter   string
	Off      int32
	Lim      int32
}

type ListStudentPaymentsRow struct {
	ID               uuid.UUID
	PaymentNumber    string
	ReceiptNumber    *string
	StudentID        uuid.UUID
	StudentFeePlanID uuid.UUID
	PaymentDate      time.Time
	Amount           pgtype.Numeric
	PaymentMethod    *string
	ReferenceNumber  *string
	Remarks          *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	BranchID         uuid.UUID
	CreatedBy        *int64
	FeeTypeName      *string
	CreatedByName    string
}

func (q *Queries) ListStudentPayments(ctx context.Context, arg ListStudentPaymentsParams) ([]ListStudentPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listStudentPayments,
		arg.BranchID,
		arg.Filter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentPaymentsRow{}
	for rows.Next() {
		var i ListStudentPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNumber,
			&i.ReceiptNumber,
			&i.StudentID,
			&i.StudentFeePlanID,
			&i.PaymentDate,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.Remarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BranchID,
			&i.CreatedBy,
			&i.FeeTypeName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPaymentSeq = `-- name: NextPaymentSeq :one
SELECT nextval('payment_seq')::bigint AS seq
`

func (q *Queries) NextPaymentSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPaymentSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const nextReceiptSeq = `-- name: NextReceiptSeq :one
SELECT nextval('receipt_seq')::bigint AS seq
`

func (q *Queries) NextReceiptSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextReceiptSeq)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateStudentPayment = `-- name: UpdateStudentPayment :one
UPDATE student_payments SET
    payment_date = $1,
    amount = $2,
    payment_method = $3,
    reference_number = $4,
    remarks = $5,
    updated_at = now()
WHERE id = $6
RETURNING id, payment_number, receipt_number, student_id, student_fee_plan_id, payment_date, amount, payment_method, reference_number, remarks, created_at, updated_at, branch_id, created_by
`

type UpdateStudentPaymentParams struct {
	PaymentDate     time.Time
	Amount          pgtype.Numeric
	PaymentMethod   *string
	ReferenceNumber *string
	Remarks         *string
	ID              uuid.UUID
}

func (q *Queries) UpdateStudentPayment(ctx context.Context, arg UpdateStudentPaymentParams) (StudentPayment, error) {
	row := q.db.QueryRow(ctx, updateStudentPayment,
		arg.PaymentDate,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.Remarks,
		arg.ID,
	)
	var i StudentPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentNumber,
		&i.ReceiptNumber,
		&i.StudentID,
		&i.StudentFeePlanID,
		&i.PaymentDate,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BranchID,
		&i.CreatedBy,
	)
	return i, err
}
