// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sequences.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const countStudentCodeSequences = `-- name: CountStudentCodeSequences :one
SELECT count(*) FROM student_code_sequences
`

func (q *Queries) CountStudentCodeSequences(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentCodeSequences)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentCodeSequence = `-- name: CreateStudentCodeSequence :one
INSERT INTO student_code_sequences (year_config_id, current_number, last_generated_code)
VALUES ($1, $2, $3)
RETURNING id, year_config_id, current_number, last_generated_code, updated_at
`

type CreateStudentCodeSequenceParams struct {
	YearConfigID      uuid.UUID
	CurrentNumber     int64
	LastGeneratedCode *string
}

func (q *Queries) CreateStudentCodeSequence(ctx context.Context, arg CreateStudentCodeSequenceParams) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, createStudentCodeSequence, arg.YearConfigID, arg.CurrentNumber, arg.LastGeneratedCode)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudentCodeSequence = `-- name: DeleteStudentCodeSequence :execrows
DELETE FROM student_code_sequences WHERE id = $1
`

func (q *Queries) DeleteStudentCodeSequence(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentCodeSequence, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSequenceExists = `-- name: EnsureSequenceExists :exec
INSERT INTO student_code_sequences (year_config_id, current_number)
VALUES ($1, 0)
ON CONFLICT (year_config_id) DO NOTHING
`

func (q *Queries) EnsureSequenceExists(ctx context.Context, yearConfigID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureSequenceExists, yearConfigID)
	return err
}

const getSequenceByYearConfig = `-- name: GetSequenceByYearConfig :one
SELECT id, year_config_id, current_number, last_generated_code, updated_at FROM student_code_sequences WHERE year_config_id = $1
`

func (q *Queries) GetSequenceByYearConfig(ctx context.Context, yearConfigID uuid.UUID) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByYearConfig, yearConfigID)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getSequenceByYearConfigForUpdate = `-- name: GetSequenceByYearConfigForUpdate :one
SELECT id, year_config_id, current_number, last_generated_code, updated_at FROM student_code_sequences
WHERE year_config_id = $1
FOR UPDATE
`

func (q *Queries) GetSequenceByYearConfigForUpdate(ctx context.Context, yearConfigID uuid.UUID) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByYearConfigForUpdate, yearConfigID)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentCodeSequence = `-- name: GetStudentCodeSequence :one
SELECT id, year_config_id, current_number, last_generated_code, updated_at FROM student_code_sequences WHERE id = $1
`

func (q *Queries) GetStudentCodeSequence(ctx context.Context, id uuid.UUID) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, getStudentCodeSequence, id)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentCodeSequences = `-- name: ListStudentCodeSequences :many
SELECT id, year_config_id, current_number, last_generated_code, updated_at FROM student_code_sequences
ORDER BY updated_at DESC
LIMIT $2 OFFSET $1
`

type ListStudentCodeSequencesParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListStudentCodeSequences(ctx context.Context, arg ListStudentCodeSequencesParams) ([]StudentCodeSequence, error) {
	rows, err := q.db.Query(ctx, listStudentCodeSequences, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCodeSequence{}
	for rows.Next() {
		var i StudentCodeSequence
		if err := rows.Scan(
			&i.ID,
			&i.YearConfigID,
			&i.CurrentNumber,
			&i.LastGeneratedCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSequenceValue = `-- name: SetSequenceValue :one
UPDATE student_code_sequences
SET current_number = $1,
    last_generated_code = $2,
    updated_at = now()
WHERE year_config_id = $3
RETURNING id, year_config_id, current_number, last_generated_code, updated_at
`

type SetSequenceValueParams struct {
	CurrentNumber     int64
	LastGeneratedCode *string
	YearConfigID      uuid.UUID
}

func (q *Queries) SetSequenceValue(ctx context.Context, arg SetSequenceValueParams) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, setSequenceValue, arg.CurrentNumber, arg.LastGeneratedCode, arg.YearConfigID)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudentCodeSequence = `-- name: UpdateStudentCodeSequence :one
UPDATE student_code_sequences
SET current_number = $1,
    last_generated_code = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, year_config_id, current_number, last_generated_code, updated_at
`

type UpdateStudentCodeSequenceParams struct {
	CurrentNumber     int64
	LastGeneratedCode *string
	ID                uuid.UUID
}

func (q *Queries) UpdateStudentCodeSequence(ctx context.Context, arg UpdateStudentCodeSequenceParams) (StudentCodeSequence, error) {
	row := q.db.QueryRow(ctx, updateStudentCodeSequence, arg.CurrentNumber, arg.LastGeneratedCode, arg.ID)
	var i StudentCodeSequence
	err := row.Scan(
		&i.ID,
		&i.YearConfigID,
		&i.CurrentNumber,
		&i.LastGeneratedCode,
		&i.UpdatedAt,
	)
	return i, err
}
