// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package tenant

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countStudents = `-- name: CountStudents :one
SELECT count(*) FROM students
WHERE deleted_at IS NULL
  AND students.branch_id = $1
  AND ($2::text = ''
       OR student_code ILIKE '%'||$2||'%'
       OR full_name ILIKE '%'||$2||'%'
       OR primary_mobile ILIKE '%'||$2||'%'
       OR city ILIKE '%'||$2||'%'
       OR EXISTS (
           SELECT 1 FROM student_assigned_codes sac
           WHERE sac.student_id = students.id
             AND sac.student_code ILIKE '%'||$2||'%'
       ))
  AND ($3::uuid IS NULL 
       OR EXISTS (
           SELECT 1 FROM student_applications sa 
           WHERE sa.student_id = students.id 
             AND sa.application_type_id = $3::uuid 
             AND sa.deleted_at IS NULL
       ))
`

type CountStudentsParams struct {
	BranchID          uuid.UUID
	Filter            string
	ApplicationTypeID *uuid.UUID
}

func (q *Queries) CountStudents(ctx context.Context, arg CountStudentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents, arg.BranchID, arg.Filter, arg.ApplicationTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    student_code, category_id, caste_id, branch_id, year_config_id,
    full_name, father_name, mother_name, gender, email,
    primary_mobile, secondary_mobile, whatsapp_mobile,
    home_address, city, state, pincode,
    school_name, passing_board, tenth_passing_year, twelfth_passing_year,
    scholarship_uid, scholarship_password, profile_photo_url,
    status, remarks, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21,
    $22, $23, $24,
    $25, $26, $27, $28
)
RETURNING id, student_code, category_id, year_config_id, father_name, mother_name, gender, email, primary_mobile, secondary_mobile, whatsapp_mobile, home_address, city, state, pincode, school_name, passing_board, tenth_passing_year, twelfth_passing_year, scholarship_uid, scholarship_password, profile_photo_url, status, remarks, created_by, updated_by, created_at, updated_at, deleted_at, full_name, caste_id, branch_id
`

type CreateStudentParams struct {
	StudentCode         string
	CategoryID          uuid.UUID
	CasteID             *uuid.UUID
	BranchID            uuid.UUID
	YearConfigID        *uuid.UUID
	FullName            string
	FatherName          *string
	MotherName          *string
	Gender              *string
	Email               *string
	PrimaryMobile       string
	SecondaryMobile     *string
	WhatsappMobile      *string
	HomeAddress         *string
	City                *string
	State               *string
	Pincode             *string
	SchoolName          *string
	PassingBoard        *string
	TenthPassingYear    *int32
	TwelfthPassingYear  *int32
	ScholarshipUid      *string
	ScholarshipPassword *string
	ProfilePhotoUrl     *string
	Status              string
	Remarks             *string
	CreatedBy           *int64
	UpdatedBy           *int64
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.StudentCode,
		arg.CategoryID,
		arg.CasteID,
		arg.BranchID,
		arg.YearConfigID,
		arg.FullName,
		arg.FatherName,
		arg.MotherName,
		arg.Gender,
		arg.Email,
		arg.PrimaryMobile,
		arg.SecondaryMobile,
		arg.WhatsappMobile,
		arg.HomeAddress,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.SchoolName,
		arg.PassingBoard,
		arg.TenthPassingYear,
		arg.TwelfthPassingYear,
		arg.ScholarshipUid,
		arg.ScholarshipPassword,
		arg.ProfilePhotoUrl,
		arg.Status,
		arg.Remarks,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.CategoryID,
		&i.YearConfigID,
		&i.FatherName,
		&i.MotherName,
		&i.Gender,
		&i.Email,
		&i.PrimaryMobile,
		&i.SecondaryMobile,
		&i.WhatsappMobile,
		&i.HomeAddress,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.SchoolName,
		&i.PassingBoard,
		&i.TenthPassingYear,
		&i.TwelfthPassingYear,
		&i.ScholarshipUid,
		&i.ScholarshipPassword,
		&i.ProfilePhotoUrl,
		&i.Status,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FullName,
		&i.CasteID,
		&i.BranchID,
	)
	return i, err
}

const exportStudents = `-- name: ExportStudents :many
SELECT 
    s.id, s.student_code, s.category_id, s.year_config_id, s.father_name, s.mother_name, s.gender, s.email, s.primary_mobile, s.secondary_mobile, s.whatsapp_mobile, s.home_address, s.city, s.state, s.pincode, s.school_name, s.passing_board, s.tenth_passing_year, s.twelfth_passing_year, s.scholarship_uid, s.scholarship_password, s.profile_photo_url, s.status, s.remarks, s.created_by, s.updated_by, s.created_at, s.updated_at, s.deleted_at, s.full_name, s.caste_id, s.branch_id,
    c.name AS category_name,
    ca.name AS caste_name
FROM students s
LEFT JOIN student_categories c ON c.id = s.category_id
LEFT JOIN student_castes ca ON ca.id = s.caste_id
WHERE s.deleted_at IS NULL
  AND s.branch_id = $1
  AND ($2::text = ''
       OR s.student_code ILIKE '%'||$2||'%'
       OR s.full_name ILIKE '%'||$2||'%'
       OR s.primary_mobile ILIKE '%'||$2||'%'
       OR s.city ILIKE '%'||$2||'%'
       OR EXISTS (
           SELECT 1 FROM student_assigned_codes sac
           WHERE sac.student_id = s.id
             AND sac.student_code ILIKE '%'||$2||'%'
       ))
  AND ($3::uuid IS NULL 
       OR EXISTS (
           SELECT 1 FROM student_applications sa 
           WHERE sa.student_id = s.id 
             AND sa.application_type_id = $3::uuid 
             AND sa.deleted_at IS NULL
       ))
ORDER BY s.created_at DESC
`

type ExportStudentsParams struct {
	BranchID          uuid.UUID
	Filter            string
	ApplicationTypeID *uuid.UUID
}

type ExportStudentsRow struct {
	ID                  uuid.UUID
	StudentCode         string
	CategoryID          uuid.UUID
	YearConfigID        *uuid.UUID
	FatherName          *string
	MotherName          *string
	Gender              *string
	Email               *string
	PrimaryMobile       string
	SecondaryMobile     *string
	WhatsappMobile      *string
	HomeAddress         *string
	City                *string
	State               *string
	Pincode             *string
	SchoolName          *string
	PassingBoard        *string
	TenthPassingYear    *int32
	TwelfthPassingYear  *int32
	ScholarshipUid      *string
	ScholarshipPassword *string
	ProfilePhotoUrl     *string
	Status              string
	Remarks             *string
	CreatedBy           *int64
	UpdatedBy           *int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           *time.Time
	FullName            string
	CasteID             *uuid.UUID
	BranchID            uuid.UUID
	CategoryName        *string
	CasteName           *string
}

func (q *Queries) ExportStudents(ctx context.Context, arg ExportStudentsParams) ([]ExportStudentsRow, error) {
	rows, err := q.db.Query(ctx, exportStudents, arg.BranchID, arg.Filter, arg.ApplicationTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportStudentsRow{}
	for rows.Next() {
		var i ExportStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.CategoryID,
			&i.YearConfigID,
			&i.FatherName,
			&i.MotherName,
			&i.Gender,
			&i.Email,
			&i.PrimaryMobile,
			&i.SecondaryMobile,
			&i.WhatsappMobile,
			&i.HomeAddress,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.SchoolName,
			&i.PassingBoard,
			&i.TenthPassingYear,
			&i.TwelfthPassingYear,
			&i.ScholarshipUid,
			&i.ScholarshipPassword,
			&i.ProfilePhotoUrl,
			&i.Status,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.CasteID,
			&i.BranchID,
			&i.CategoryName,
			&i.CasteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudent = `-- name: GetStudent :one
SELECT id, student_code, category_id, year_config_id, father_name, mother_name, gender, email, primary_mobile, secondary_mobile, whatsapp_mobile, home_address, city, state, pincode, school_name, passing_board, tenth_passing_year, twelfth_passing_year, scholarship_uid, scholarship_password, profile_photo_url, status, remarks, created_by, updated_by, created_at, updated_at, deleted_at, full_name, caste_id, branch_id FROM students WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStudent(ctx context.Context, id uuid.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.CategoryID,
		&i.YearConfigID,
		&i.FatherName,
		&i.MotherName,
		&i.Gender,
		&i.Email,
		&i.PrimaryMobile,
		&i.SecondaryMobile,
		&i.WhatsappMobile,
		&i.HomeAddress,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.SchoolName,
		&i.PassingBoard,
		&i.TenthPassingYear,
		&i.TwelfthPassingYear,
		&i.ScholarshipUid,
		&i.ScholarshipPassword,
		&i.ProfilePhotoUrl,
		&i.Status,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FullName,
		&i.CasteID,
		&i.BranchID,
	)
	return i, err
}

const getStudentByCode = `-- name: GetStudentByCode :one
SELECT id, student_code, category_id, year_config_id, father_name, mother_name, gender, email, primary_mobile, secondary_mobile, whatsapp_mobile, home_address, city, state, pincode, school_name, passing_board, tenth_passing_year, twelfth_passing_year, scholarship_uid, scholarship_password, profile_photo_url, status, remarks, created_by, updated_by, created_at, updated_at, deleted_at, full_name, caste_id, branch_id FROM students WHERE student_code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStudentByCode(ctx context.Context, studentCode string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByCode, studentCode)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.CategoryID,
		&i.YearConfigID,
		&i.FatherName,
		&i.MotherName,
		&i.Gender,
		&i.Email,
		&i.PrimaryMobile,
		&i.SecondaryMobile,
		&i.WhatsappMobile,
		&i.HomeAddress,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.SchoolName,
		&i.PassingBoard,
		&i.TenthPassingYear,
		&i.TwelfthPassingYear,
		&i.ScholarshipUid,
		&i.ScholarshipPassword,
		&i.ProfilePhotoUrl,
		&i.Status,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FullName,
		&i.CasteID,
		&i.BranchID,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_code, category_id, year_config_id, father_name, mother_name, gender, email, primary_mobile, secondary_mobile, whatsapp_mobile, home_address, city, state, pincode, school_name, passing_board, tenth_passing_year, twelfth_passing_year, scholarship_uid, scholarship_password, profile_photo_url, status, remarks, created_by, updated_by, created_at, updated_at, deleted_at, full_name, caste_id, branch_id FROM students
WHERE deleted_at IS NULL
  AND students.branch_id = $1
  AND ($2::text = ''
       OR student_code ILIKE '%'||$2||'%'
       OR full_name ILIKE '%'||$2||'%'
       OR primary_mobile ILIKE '%'||$2||'%'
       OR city ILIKE '%'||$2||'%'
       OR EXISTS (
           SELECT 1 FROM student_assigned_codes sac
           WHERE sac.student_id = students.id
             AND sac.student_code ILIKE '%'||$2||'%'
       ))
  AND ($3::uuid IS NULL 
       OR EXISTS (
           SELECT 1 FROM student_applications sa 
           WHERE sa.student_id = students.id 
             AND sa.application_type_id = $3::uuid 
             AND sa.deleted_at IS NULL
       ))
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListStudentsParams struct {
	BranchID          uuid.UUID
	Filter            string
	ApplicationTypeID *uuid.UUID
	Off               int32
	Lim               int32
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.BranchID,
		arg.Filter,
		arg.ApplicationTypeID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentCode,
			&i.CategoryID,
			&i.YearConfigID,
			&i.FatherName,
			&i.MotherName,
			&i.Gender,
			&i.Email,
			&i.PrimaryMobile,
			&i.SecondaryMobile,
			&i.WhatsappMobile,
			&i.HomeAddress,
			&i.City,
			&i.State,
			&i.Pincode,
			&i.SchoolName,
			&i.PassingBoard,
			&i.TenthPassingYear,
			&i.TwelfthPassingYear,
			&i.ScholarshipUid,
			&i.ScholarshipPassword,
			&i.ProfilePhotoUrl,
			&i.Status,
			&i.Remarks,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FullName,
			&i.CasteID,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStudent = `-- name: SoftDeleteStudent :execrows
UPDATE students SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStudent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteStudent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET
    category_id = $1,
    year_config_id = $2,
    student_code = $3,
    caste_id = $4,
    branch_id = $5,
    full_name = $6,
    father_name = $7,
    mother_name = $8,
    gender = $9,
    email = $10,
    primary_mobile = $11,
    secondary_mobile = $12,
    whatsapp_mobile = $13,
    home_address = $14,
    city = $15,
    state = $16,
    pincode = $17,
    school_name = $18,
    passing_board = $19,
    tenth_passing_year = $20,
    twelfth_passing_year = $21,
    scholarship_uid = $22,
    scholarship_password = $23,
    profile_photo_url = $24,
    status = $25,
    remarks = $26,
    updated_by = $27,
    updated_at = now()
WHERE id = $28 AND deleted_at IS NULL
RETURNING id, student_code, category_id, year_config_id, father_name, mother_name, gender, email, primary_mobile, secondary_mobile, whatsapp_mobile, home_address, city, state, pincode, school_name, passing_board, tenth_passing_year, twelfth_passing_year, scholarship_uid, scholarship_password, profile_photo_url, status, remarks, created_by, updated_by, created_at, updated_at, deleted_at, full_name, caste_id, branch_id
`

type UpdateStudentParams struct {
	CategoryID          uuid.UUID
	YearConfigID        *uuid.UUID
	StudentCode         string
	CasteID             *uuid.UUID
	BranchID            uuid.UUID
	FullName            string
	FatherName          *string
	MotherName          *string
	Gender              *string
	Email               *string
	PrimaryMobile       string
	SecondaryMobile     *string
	WhatsappMobile      *string
	HomeAddress         *string
	City                *string
	State               *string
	Pincode             *string
	SchoolName          *string
	PassingBoard        *string
	TenthPassingYear    *int32
	TwelfthPassingYear  *int32
	ScholarshipUid      *string
	ScholarshipPassword *string
	ProfilePhotoUrl     *string
	Status              string
	Remarks             *string
	UpdatedBy           *int64
	ID                  uuid.UUID
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.CategoryID,
		arg.YearConfigID,
		arg.StudentCode,
		arg.CasteID,
		arg.BranchID,
		arg.FullName,
		arg.FatherName,
		arg.MotherName,
		arg.Gender,
		arg.Email,
		arg.PrimaryMobile,
		arg.SecondaryMobile,
		arg.WhatsappMobile,
		arg.HomeAddress,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.SchoolName,
		arg.PassingBoard,
		arg.TenthPassingYear,
		arg.TwelfthPassingYear,
		arg.ScholarshipUid,
		arg.ScholarshipPassword,
		arg.ProfilePhotoUrl,
		arg.Status,
		arg.Remarks,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentCode,
		&i.CategoryID,
		&i.YearConfigID,
		&i.FatherName,
		&i.MotherName,
		&i.Gender,
		&i.Email,
		&i.PrimaryMobile,
		&i.SecondaryMobile,
		&i.WhatsappMobile,
		&i.HomeAddress,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.SchoolName,
		&i.PassingBoard,
		&i.TenthPassingYear,
		&i.TwelfthPassingYear,
		&i.ScholarshipUid,
		&i.ScholarshipPassword,
		&i.ProfilePhotoUrl,
		&i.Status,
		&i.Remarks,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FullName,
		&i.CasteID,
		&i.BranchID,
	)
	return i, err
}
