// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_assigned_codes.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const createAssignedCode = `-- name: CreateAssignedCode :one
INSERT INTO student_assigned_codes (
    student_id, category_id, year_config_id, student_code
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, student_id, category_id, year_config_id, student_code, created_at
`

type CreateAssignedCodeParams struct {
	StudentID    uuid.UUID
	CategoryID   uuid.UUID
	YearConfigID uuid.UUID
	StudentCode  string
}

func (q *Queries) CreateAssignedCode(ctx context.Context, arg CreateAssignedCodeParams) (StudentAssignedCode, error) {
	row := q.db.QueryRow(ctx, createAssignedCode,
		arg.StudentID,
		arg.CategoryID,
		arg.YearConfigID,
		arg.StudentCode,
	)
	var i StudentAssignedCode
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CategoryID,
		&i.YearConfigID,
		&i.StudentCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignedCodeByCategory = `-- name: GetAssignedCodeByCategory :one
SELECT id, student_id, category_id, year_config_id, student_code, created_at FROM student_assigned_codes
WHERE student_id = $1 AND category_id = $2
`

type GetAssignedCodeByCategoryParams struct {
	StudentID  uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) GetAssignedCodeByCategory(ctx context.Context, arg GetAssignedCodeByCategoryParams) (StudentAssignedCode, error) {
	row := q.db.QueryRow(ctx, getAssignedCodeByCategory, arg.StudentID, arg.CategoryID)
	var i StudentAssignedCode
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CategoryID,
		&i.YearConfigID,
		&i.StudentCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAssignedCodesByStudent = `-- name: GetAssignedCodesByStudent :many
SELECT id, student_id, category_id, year_config_id, student_code, created_at FROM student_assigned_codes
WHERE student_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAssignedCodesByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentAssignedCode, error) {
	rows, err := q.db.Query(ctx, getAssignedCodesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentAssignedCode{}
	for rows.Next() {
		var i StudentAssignedCode
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CategoryID,
			&i.YearConfigID,
			&i.StudentCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignedCodesByStudentIDs = `-- name: GetAssignedCodesByStudentIDs :many
SELECT id, student_id, category_id, year_config_id, student_code, created_at FROM student_assigned_codes
WHERE student_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) GetAssignedCodesByStudentIDs(ctx context.Context, studentIds []uuid.UUID) ([]StudentAssignedCode, error) {
	rows, err := q.db.Query(ctx, getAssignedCodesByStudentIDs, studentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentAssignedCode{}
	for rows.Next() {
		var i StudentAssignedCode
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CategoryID,
			&i.YearConfigID,
			&i.StudentCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
