// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: yearconfigs.sql

package tenant

import (
	"context"

	"github.com/google/uuid"
)

const checkYearConfigInUse = `-- name: CheckYearConfigInUse :one
SELECT EXISTS(SELECT 1 FROM students WHERE year_config_id = $1::uuid)
`

func (q *Queries) CheckYearConfigInUse(ctx context.Context, dollar_1 uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkYearConfigInUse, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countStudentCodeConfigs = `-- name: CountStudentCodeConfigs :one
SELECT count(*) FROM student_code_year_configs
WHERE ($1::text = '' OR prefix ILIKE '%'||$1||'%')
`

func (q *Queries) CountStudentCodeConfigs(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentCodeConfigs, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudentCodeConfig = `-- name: CreateStudentCodeConfig :one
INSERT INTO student_code_year_configs
    (category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active)
VALUES
    ($1, $2, $3, $4,
     $5, $6, $7)
RETURNING id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at
`

type CreateStudentCodeConfigParams struct {
	CategoryID    uuid.UUID
	BusinessYear  int32
	Prefix        string
	Separator     string
	PaddingLength int32
	ResetSequence bool
	IsActive      bool
}

func (q *Queries) CreateStudentCodeConfig(ctx context.Context, arg CreateStudentCodeConfigParams) (StudentCodeYearConfig, error) {
	row := q.db.QueryRow(ctx, createStudentCodeConfig,
		arg.CategoryID,
		arg.BusinessYear,
		arg.Prefix,
		arg.Separator,
		arg.PaddingLength,
		arg.ResetSequence,
		arg.IsActive,
	)
	var i StudentCodeYearConfig
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BusinessYear,
		&i.Prefix,
		&i.Separator,
		&i.PaddingLength,
		&i.ResetSequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudentCodeConfig = `-- name: DeleteStudentCodeConfig :execrows
DELETE FROM student_code_year_configs WHERE id = $1
`

func (q *Queries) DeleteStudentCodeConfig(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentCodeConfig, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveConfigByCategory = `-- name: GetActiveConfigByCategory :one
SELECT id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at FROM student_code_year_configs
WHERE category_id = $1 AND is_active = TRUE
ORDER BY business_year DESC
LIMIT 1
`

func (q *Queries) GetActiveConfigByCategory(ctx context.Context, categoryID uuid.UUID) (StudentCodeYearConfig, error) {
	row := q.db.QueryRow(ctx, getActiveConfigByCategory, categoryID)
	var i StudentCodeYearConfig
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BusinessYear,
		&i.Prefix,
		&i.Separator,
		&i.PaddingLength,
		&i.ResetSequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveConfigByCategoryYear = `-- name: GetActiveConfigByCategoryYear :one
SELECT id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at FROM student_code_year_configs
WHERE category_id = $1 AND business_year = $2 AND is_active = TRUE
LIMIT 1
`

type GetActiveConfigByCategoryYearParams struct {
	CategoryID   uuid.UUID
	BusinessYear int32
}

func (q *Queries) GetActiveConfigByCategoryYear(ctx context.Context, arg GetActiveConfigByCategoryYearParams) (StudentCodeYearConfig, error) {
	row := q.db.QueryRow(ctx, getActiveConfigByCategoryYear, arg.CategoryID, arg.BusinessYear)
	var i StudentCodeYearConfig
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BusinessYear,
		&i.Prefix,
		&i.Separator,
		&i.PaddingLength,
		&i.ResetSequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentCodeConfig = `-- name: GetStudentCodeConfig :one
SELECT id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at FROM student_code_year_configs WHERE id = $1
`

func (q *Queries) GetStudentCodeConfig(ctx context.Context, id uuid.UUID) (StudentCodeYearConfig, error) {
	row := q.db.QueryRow(ctx, getStudentCodeConfig, id)
	var i StudentCodeYearConfig
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BusinessYear,
		&i.Prefix,
		&i.Separator,
		&i.PaddingLength,
		&i.ResetSequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudentCodeConfigs = `-- name: ListStudentCodeConfigs :many
SELECT id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at FROM student_code_year_configs
WHERE ($1::text = '' OR prefix ILIKE '%'||$1||'%')
ORDER BY business_year DESC, prefix ASC
LIMIT $3 OFFSET $2
`

type ListStudentCodeConfigsParams struct {
	Filter string
	Off    int32
	Lim    int32
}

func (q *Queries) ListStudentCodeConfigs(ctx context.Context, arg ListStudentCodeConfigsParams) ([]StudentCodeYearConfig, error) {
	rows, err := q.db.Query(ctx, listStudentCodeConfigs, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCodeYearConfig{}
	for rows.Next() {
		var i StudentCodeYearConfig
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BusinessYear,
			&i.Prefix,
			&i.Separator,
			&i.PaddingLength,
			&i.ResetSequence,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentCodeConfig = `-- name: UpdateStudentCodeConfig :one
UPDATE student_code_year_configs
SET category_id = $1,
    business_year = $2,
    prefix = $3,
    separator = $4,
    padding_length = $5,
    reset_sequence = $6,
    is_active = $7,
    updated_at = now()
WHERE id = $8
RETURNING id, category_id, business_year, prefix, separator, padding_length, reset_sequence, is_active, created_at, updated_at
`

type UpdateStudentCodeConfigParams struct {
	CategoryID    uuid.UUID
	BusinessYear  int32
	Prefix        string
	Separator     string
	PaddingLength int32
	ResetSequence bool
	IsActive      bool
	ID            uuid.UUID
}

func (q *Queries) UpdateStudentCodeConfig(ctx context.Context, arg UpdateStudentCodeConfigParams) (StudentCodeYearConfig, error) {
	row := q.db.QueryRow(ctx, updateStudentCodeConfig,
		arg.CategoryID,
		arg.BusinessYear,
		arg.Prefix,
		arg.Separator,
		arg.PaddingLength,
		arg.ResetSequence,
		arg.IsActive,
		arg.ID,
	)
	var i StudentCodeYearConfig
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BusinessYear,
		&i.Prefix,
		&i.Separator,
		&i.PaddingLength,
		&i.ResetSequence,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
