// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authtokens.sql

package public

import (
	"context"
	"time"
)

const consumeAuthToken = `-- name: ConsumeAuthToken :exec
UPDATE auth_tokens SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeAuthToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeAuthToken, id)
	return err
}

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthTokenByHash = `-- name: GetAuthTokenByHash :one
SELECT id, user_id, token_hash, purpose, expires_at, consumed_at, created_at FROM auth_tokens
WHERE token_hash = $1 AND purpose = $2
  AND consumed_at IS NULL AND expires_at > now()
`

type GetAuthTokenByHashParams struct {
	TokenHash string
	Purpose   string
}

func (q *Queries) GetAuthTokenByHash(ctx context.Context, arg GetAuthTokenByHashParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, getAuthTokenByHash, arg.TokenHash, arg.Purpose)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestOTP = `-- name: GetLatestOTP :one
SELECT id, email, code_hash, purpose, attempts, expires_at, consumed_at, created_at FROM otp_codes
WHERE lower(email) = lower($1) AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestOTPParams struct {
	Email   string
	Purpose string
}

func (q *Queries) GetLatestOTP(ctx context.Context, arg GetLatestOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestOTP, arg.Email, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, tenant_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const insertAuthToken = `-- name: InsertAuthToken :one
INSERT INTO auth_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, expires_at, consumed_at, created_at
`

type InsertAuthTokenParams struct {
	UserID    int64
	TokenHash string
	Purpose   string
	ExpiresAt time.Time
}

// ── Email-verification / set-password tokens ────────────────────────────
func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRow(ctx, insertAuthToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertOTP = `-- name: InsertOTP :one
INSERT INTO otp_codes (email, code_hash, purpose, expires_at)
VALUES (lower($1), $2, $3, $4)
RETURNING id, email, code_hash, purpose, attempts, expires_at, consumed_at, created_at
`

type InsertOTPParams struct {
	Email     string
	CodeHash  string
	Purpose   string
	ExpiresAt time.Time
}

// ── OTP codes ───────────────────────────────────────────────────────────
func (q *Queries) InsertOTP(ctx context.Context, arg InsertOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, insertOTP,
		arg.Email,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, tenant_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tenant_id, token_hash, user_agent, ip_address, expires_at, revoked_at, created_at
`

type InsertRefreshTokenParams struct {
	UserID    int64
	TenantID  *int64
	TokenHash string
	UserAgent *string
	IpAddress *string
	ExpiresAt time.Time
}

// ── Refresh tokens ──────────────────────────────────────────────────────
func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
