// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_documents.sql

package public

import (
	"context"
	"time"
)

const checkDocumentAccess = `-- name: CheckDocumentAccess :one
SELECT id, document_id, connection_id, granted_at FROM document_access_grants
WHERE document_id = $1 AND connection_id = $2
`

type CheckDocumentAccessParams struct {
	DocumentID   int64
	ConnectionID int64
}

func (q *Queries) CheckDocumentAccess(ctx context.Context, arg CheckDocumentAccessParams) (DocumentAccessGrant, error) {
	row := q.db.QueryRow(ctx, checkDocumentAccess, arg.DocumentID, arg.ConnectionID)
	var i DocumentAccessGrant
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ConnectionID,
		&i.GrantedAt,
	)
	return i, err
}

const createClientDocument = `-- name: CreateClientDocument :one
INSERT INTO client_documents (
    client_id, document_type_id, file_name, original_file_name, file_size, mime_type, sha256_hash, storage_path, uploaded_by, source
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, client_id, document_type_id, file_name, original_file_name, file_size, mime_type, sha256_hash, storage_path, uploaded_by, source, created_at, updated_at
`

type CreateClientDocumentParams struct {
	ClientID         int64
	DocumentTypeID   int64
	FileName         string
	OriginalFileName string
	FileSize         int64
	MimeType         string
	Sha256Hash       *string
	StoragePath      string
	UploadedBy       *int64
	Source           string
}

func (q *Queries) CreateClientDocument(ctx context.Context, arg CreateClientDocumentParams) (ClientDocument, error) {
	row := q.db.QueryRow(ctx, createClientDocument,
		arg.ClientID,
		arg.DocumentTypeID,
		arg.FileName,
		arg.OriginalFileName,
		arg.FileSize,
		arg.MimeType,
		arg.Sha256Hash,
		arg.StoragePath,
		arg.UploadedBy,
		arg.Source,
	)
	var i ClientDocument
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DocumentTypeID,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.StoragePath,
		&i.UploadedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentAccessGrant = `-- name: CreateDocumentAccessGrant :one
INSERT INTO document_access_grants (document_id, connection_id)
VALUES ($1, $2)
RETURNING id, document_id, connection_id, granted_at
`

type CreateDocumentAccessGrantParams struct {
	DocumentID   int64
	ConnectionID int64
}

func (q *Queries) CreateDocumentAccessGrant(ctx context.Context, arg CreateDocumentAccessGrantParams) (DocumentAccessGrant, error) {
	row := q.db.QueryRow(ctx, createDocumentAccessGrant, arg.DocumentID, arg.ConnectionID)
	var i DocumentAccessGrant
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ConnectionID,
		&i.GrantedAt,
	)
	return i, err
}

const deleteAllDocumentAccessGrantsForConnection = `-- name: DeleteAllDocumentAccessGrantsForConnection :exec
DELETE FROM document_access_grants
WHERE connection_id = $1
`

func (q *Queries) DeleteAllDocumentAccessGrantsForConnection(ctx context.Context, connectionID int64) error {
	_, err := q.db.Exec(ctx, deleteAllDocumentAccessGrantsForConnection, connectionID)
	return err
}

const deleteClientDocument = `-- name: DeleteClientDocument :exec
DELETE FROM client_documents
WHERE id = $1
`

func (q *Queries) DeleteClientDocument(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClientDocument, id)
	return err
}

const deleteDocumentAccessGrant = `-- name: DeleteDocumentAccessGrant :exec
DELETE FROM document_access_grants
WHERE document_id = $1 AND connection_id = $2
`

type DeleteDocumentAccessGrantParams struct {
	DocumentID   int64
	ConnectionID int64
}

func (q *Queries) DeleteDocumentAccessGrant(ctx context.Context, arg DeleteDocumentAccessGrantParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentAccessGrant, arg.DocumentID, arg.ConnectionID)
	return err
}

const getClientDocument = `-- name: GetClientDocument :one
SELECT id, client_id, document_type_id, file_name, original_file_name, file_size, mime_type, sha256_hash, storage_path, uploaded_by, source, created_at, updated_at FROM client_documents
WHERE id = $1
`

func (q *Queries) GetClientDocument(ctx context.Context, id int64) (ClientDocument, error) {
	row := q.db.QueryRow(ctx, getClientDocument, id)
	var i ClientDocument
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DocumentTypeID,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.StoragePath,
		&i.UploadedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentAccessGrants = `-- name: GetDocumentAccessGrants :many
SELECT 
    dag.id, 
    dag.document_id, 
    dag.connection_id, 
    dag.granted_at,
    t.tenant_name AS organization_name
FROM document_access_grants dag
JOIN client_connections cc ON cc.id = dag.connection_id
JOIN tenants t ON t.tenant_id = cc.tenant_id
WHERE dag.document_id = $1
ORDER BY dag.granted_at DESC
`

type GetDocumentAccessGrantsRow struct {
	ID               int64
	DocumentID       int64
	ConnectionID     int64
	GrantedAt        time.Time
	OrganizationName string
}

func (q *Queries) GetDocumentAccessGrants(ctx context.Context, documentID int64) ([]GetDocumentAccessGrantsRow, error) {
	rows, err := q.db.Query(ctx, getDocumentAccessGrants, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentAccessGrantsRow{}
	for rows.Next() {
		var i GetDocumentAccessGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ConnectionID,
			&i.GrantedAt,
			&i.OrganizationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientVaultFiles = `-- name: ListClientVaultFiles :many
SELECT cd.id, cd.client_id, cd.document_type_id, cd.file_name, cd.original_file_name, cd.file_size, cd.mime_type, cd.sha256_hash, cd.storage_path, cd.uploaded_by, cd.source, cd.created_at, cd.updated_at,
    dt.name AS document_type_name,
    COALESCE(u.first_name || ' ' || u.last_name, '')::varchar AS uploaded_by_name
FROM client_documents cd
JOIN document_types dt ON dt.id = cd.document_type_id
LEFT JOIN user_profiles u ON u.user_id = cd.uploaded_by
WHERE cd.client_id = $1 AND cd.document_type_id = $2
ORDER BY cd.created_at DESC
`

type ListClientVaultFilesParams struct {
	ClientID       int64
	DocumentTypeID int64
}

type ListClientVaultFilesRow struct {
	ID               int64
	ClientID         int64
	DocumentTypeID   int64
	FileName         string
	OriginalFileName string
	FileSize         int64
	MimeType         string
	Sha256Hash       *string
	StoragePath      string
	UploadedBy       *int64
	Source           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DocumentTypeName string
	UploadedByName   string
}

func (q *Queries) ListClientVaultFiles(ctx context.Context, arg ListClientVaultFilesParams) ([]ListClientVaultFilesRow, error) {
	rows, err := q.db.Query(ctx, listClientVaultFiles, arg.ClientID, arg.DocumentTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientVaultFilesRow{}
	for rows.Next() {
		var i ListClientVaultFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DocumentTypeID,
			&i.FileName,
			&i.OriginalFileName,
			&i.FileSize,
			&i.MimeType,
			&i.Sha256Hash,
			&i.StoragePath,
			&i.UploadedBy,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DocumentTypeName,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientVaultFolders = `-- name: ListClientVaultFolders :many
SELECT 
    dt.id AS document_type_id, 
    dt.name AS document_type_name,
    COUNT(cd.id)::int AS file_count
FROM document_types dt
JOIN client_documents cd ON cd.document_type_id = dt.id
WHERE cd.client_id = $1
GROUP BY dt.id, dt.name
ORDER BY dt.name ASC
`

type ListClientVaultFoldersRow struct {
	DocumentTypeID   int64
	DocumentTypeName string
	FileCount        int32
}

func (q *Queries) ListClientVaultFolders(ctx context.Context, clientID int64) ([]ListClientVaultFoldersRow, error) {
	rows, err := q.db.Query(ctx, listClientVaultFolders, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientVaultFoldersRow{}
	for rows.Next() {
		var i ListClientVaultFoldersRow
		if err := rows.Scan(&i.DocumentTypeID, &i.DocumentTypeName, &i.FileCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientDocumentName = `-- name: UpdateClientDocumentName :one
UPDATE client_documents
SET file_name = $2, updated_at = now()
WHERE id = $1
RETURNING id, client_id, document_type_id, file_name, original_file_name, file_size, mime_type, sha256_hash, storage_path, uploaded_by, source, created_at, updated_at
`

type UpdateClientDocumentNameParams struct {
	ID       int64
	FileName string
}

func (q *Queries) UpdateClientDocumentName(ctx context.Context, arg UpdateClientDocumentNameParams) (ClientDocument, error) {
	row := q.db.QueryRow(ctx, updateClientDocumentName, arg.ID, arg.FileName)
	var i ClientDocument
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DocumentTypeID,
		&i.FileName,
		&i.OriginalFileName,
		&i.FileSize,
		&i.MimeType,
		&i.Sha256Hash,
		&i.StoragePath,
		&i.UploadedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
