// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_management.sql

package public

import (
	"context"
	"time"
)

const createClientConnection = `-- name: CreateClientConnection :one
INSERT INTO client_connections (tenant_id, client_id, status, connected_by, accepted_at, accepted_by)
VALUES ($1, $2, 'ACTIVE', $3, $4, $5)
RETURNING id, client_id, tenant_id, status, created_at, connected_by, accepted_at, accepted_by, removed_at, removed_by, status_reason
`

type CreateClientConnectionParams struct {
	TenantID    int64
	ClientID    int64
	ConnectedBy *int64
	AcceptedAt  *time.Time
	AcceptedBy  *int64
}

func (q *Queries) CreateClientConnection(ctx context.Context, arg CreateClientConnectionParams) (ClientConnection, error) {
	row := q.db.QueryRow(ctx, createClientConnection,
		arg.TenantID,
		arg.ClientID,
		arg.ConnectedBy,
		arg.AcceptedAt,
		arg.AcceptedBy,
	)
	var i ClientConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedBy,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.StatusReason,
	)
	return i, err
}

const createClientProfile = `-- name: CreateClientProfile :one
INSERT INTO client_profiles (user_id, connection_code, full_name)
VALUES ($1, $2, $3)
RETURNING id, user_id, connection_code, full_name, created_at, updated_at
`

type CreateClientProfileParams struct {
	UserID         int64
	ConnectionCode string
	FullName       *string
}

func (q *Queries) CreateClientProfile(ctx context.Context, arg CreateClientProfileParams) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, createClientProfile, arg.UserID, arg.ConnectionCode, arg.FullName)
	var i ClientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionCode,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConnectionRequest = `-- name: CreateConnectionRequest :one
INSERT INTO connection_requests (tenant_id, client_id, status)
VALUES ($1, $2, 'PENDING')
RETURNING id, client_id, tenant_id, status, created_at
`

type CreateConnectionRequestParams struct {
	TenantID int64
	ClientID int64
}

func (q *Queries) CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (ConnectionRequest, error) {
	row := q.db.QueryRow(ctx, createConnectionRequest, arg.TenantID, arg.ClientID)
	var i ConnectionRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteClientConnection = `-- name: DeleteClientConnection :exec
DELETE FROM client_connections WHERE id = $1
`

func (q *Queries) DeleteClientConnection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteClientConnection, id)
	return err
}

const getClientConnectionById = `-- name: GetClientConnectionById :one
SELECT id, client_id, tenant_id, status, created_at, connected_by, accepted_at, accepted_by, removed_at, removed_by, status_reason FROM client_connections WHERE id = $1
`

func (q *Queries) GetClientConnectionById(ctx context.Context, id int64) (ClientConnection, error) {
	row := q.db.QueryRow(ctx, getClientConnectionById, id)
	var i ClientConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedBy,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.StatusReason,
	)
	return i, err
}

const getClientConnectionByTenantAndClient = `-- name: GetClientConnectionByTenantAndClient :one
SELECT id, client_id, tenant_id, status, created_at, connected_by, accepted_at, accepted_by, removed_at, removed_by, status_reason FROM client_connections
WHERE tenant_id = $1 AND client_id = $2
`

type GetClientConnectionByTenantAndClientParams struct {
	TenantID int64
	ClientID int64
}

func (q *Queries) GetClientConnectionByTenantAndClient(ctx context.Context, arg GetClientConnectionByTenantAndClientParams) (ClientConnection, error) {
	row := q.db.QueryRow(ctx, getClientConnectionByTenantAndClient, arg.TenantID, arg.ClientID)
	var i ClientConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedBy,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.StatusReason,
	)
	return i, err
}

const getClientConnectionDetails = `-- name: GetClientConnectionDetails :one
SELECT cc.id, cc.client_id, cc.tenant_id, cc.status, cc.created_at, cc.connected_by, cc.accepted_at, cc.accepted_by, cc.removed_at, cc.removed_by, cc.status_reason, cp.connection_code, cp.full_name, cp.user_id, cp.created_at as profile_created_at, u.email, up.contact_number as phone, up.first_name, up.last_name,
       cprms.view_profile, cprms.view_documents, cprms.upload_documents, cprms.create_applications, cprms.view_applications, cprms.approve_applications, cprms.manage_connection
FROM client_connections cc
JOIN client_profiles cp ON cc.client_id = cp.id
JOIN users u ON cp.user_id = u.id
LEFT JOIN user_profiles up ON u.id = up.user_id
LEFT JOIN connection_permissions cprms ON cc.id = cprms.connection_id
WHERE cc.tenant_id = $1 AND cc.client_id = $2
`

type GetClientConnectionDetailsParams struct {
	TenantID int64
	ClientID int64
}

type GetClientConnectionDetailsRow struct {
	ID                  int64
	ClientID            int64
	TenantID            int64
	Status              string
	CreatedAt           time.Time
	ConnectedBy         *int64
	AcceptedAt          *time.Time
	AcceptedBy          *int64
	RemovedAt           *time.Time
	RemovedBy           *int64
	StatusReason        *string
	ConnectionCode      string
	FullName            *string
	UserID              int64
	ProfileCreatedAt    time.Time
	Email               string
	Phone               *string
	FirstName           *string
	LastName            *string
	ViewProfile         *bool
	ViewDocuments       *bool
	UploadDocuments     *bool
	CreateApplications  *bool
	ViewApplications    *bool
	ApproveApplications *bool
	ManageConnection    *bool
}

func (q *Queries) GetClientConnectionDetails(ctx context.Context, arg GetClientConnectionDetailsParams) (GetClientConnectionDetailsRow, error) {
	row := q.db.QueryRow(ctx, getClientConnectionDetails, arg.TenantID, arg.ClientID)
	var i GetClientConnectionDetailsRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedBy,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.StatusReason,
		&i.ConnectionCode,
		&i.FullName,
		&i.UserID,
		&i.ProfileCreatedAt,
		&i.Email,
		&i.Phone,
		&i.FirstName,
		&i.LastName,
		&i.ViewProfile,
		&i.ViewDocuments,
		&i.UploadDocuments,
		&i.CreateApplications,
		&i.ViewApplications,
		&i.ApproveApplications,
		&i.ManageConnection,
	)
	return i, err
}

const getClientConnections = `-- name: GetClientConnections :many
SELECT cc.id, cc.client_id, cc.tenant_id, cc.status, cc.created_at, cc.connected_by, cc.accepted_at, cc.accepted_by, cc.removed_at, cc.removed_by, cc.status_reason, cp.connection_code, cp.full_name, cp.user_id, u.email, up.contact_number as phone, up.first_name, up.last_name
FROM client_connections cc
JOIN client_profiles cp ON cc.client_id = cp.id
JOIN users u ON cp.user_id = u.id
LEFT JOIN user_profiles up ON u.id = up.user_id
WHERE cc.tenant_id = $1
AND (NULLIF($2::text, '') IS NULL OR cc.status = $2)
AND (NULLIF($5::text, '') IS NULL OR cp.full_name ILIKE '%' || $5 || '%' OR cp.connection_code ILIKE '%' || $5 || '%' OR u.email ILIKE '%' || $5 || '%' OR up.first_name ILIKE '%' || $5 || '%' OR up.last_name ILIKE '%' || $5 || '%')
ORDER BY cc.created_at DESC
LIMIT $4 OFFSET $3
`

type GetClientConnectionsParams struct {
	TenantID int64
	Column2  string
	Offset   int32
	Limit    int32
	Column5  string
}

type GetClientConnectionsRow struct {
	ID             int64
	ClientID       int64
	TenantID       int64
	Status         string
	CreatedAt      time.Time
	ConnectedBy    *int64
	AcceptedAt     *time.Time
	AcceptedBy     *int64
	RemovedAt      *time.Time
	RemovedBy      *int64
	StatusReason   *string
	ConnectionCode string
	FullName       *string
	UserID         int64
	Email          string
	Phone          *string
	FirstName      *string
	LastName       *string
}

func (q *Queries) GetClientConnections(ctx context.Context, arg GetClientConnectionsParams) ([]GetClientConnectionsRow, error) {
	rows, err := q.db.Query(ctx, getClientConnections,
		arg.TenantID,
		arg.Column2,
		arg.Offset,
		arg.Limit,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClientConnectionsRow{}
	for rows.Next() {
		var i GetClientConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TenantID,
			&i.Status,
			&i.CreatedAt,
			&i.ConnectedBy,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RemovedAt,
			&i.RemovedBy,
			&i.StatusReason,
			&i.ConnectionCode,
			&i.FullName,
			&i.UserID,
			&i.Email,
			&i.Phone,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientProfileByCode = `-- name: GetClientProfileByCode :one
SELECT id, user_id, connection_code, full_name, created_at, updated_at FROM client_profiles
WHERE connection_code = $1 LIMIT 1
`

func (q *Queries) GetClientProfileByCode(ctx context.Context, connectionCode string) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, getClientProfileByCode, connectionCode)
	var i ClientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionCode,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientProfileByUserId = `-- name: GetClientProfileByUserId :one
SELECT id, user_id, connection_code, full_name, created_at, updated_at FROM client_profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetClientProfileByUserId(ctx context.Context, userID int64) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, getClientProfileByUserId, userID)
	var i ClientProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionCode,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectedOrganizationsForClient = `-- name: GetConnectedOrganizationsForClient :many
SELECT cc.id, cc.client_id, cc.tenant_id, cc.status, cc.created_at, cc.connected_by, cc.accepted_at, cc.accepted_by, cc.removed_at, cc.removed_by, cc.status_reason, 
       t.company_name as tenant_name,
       cp.contact_email,
       cp.contact_phone,
       cp.address_line1,
       cp.address_line2,
       cp.city,
       cp.state,
       cp.country,
       cp.postal_code
FROM client_connections cc
JOIN tenants t ON cc.tenant_id = t.tenant_id
LEFT JOIN company_profiles cp ON t.tenant_id = cp.tenant_id
WHERE cc.client_id = $1
ORDER BY cc.created_at DESC
`

type GetConnectedOrganizationsForClientRow struct {
	ID           int64
	ClientID     int64
	TenantID     int64
	Status       string
	CreatedAt    time.Time
	ConnectedBy  *int64
	AcceptedAt   *time.Time
	AcceptedBy   *int64
	RemovedAt    *time.Time
	RemovedBy    *int64
	StatusReason *string
	TenantName   *string
	ContactEmail *string
	ContactPhone *string
	AddressLine1 *string
	AddressLine2 *string
	City         *string
	State        *string
	Country      *string
	PostalCode   *string
}

func (q *Queries) GetConnectedOrganizationsForClient(ctx context.Context, clientID int64) ([]GetConnectedOrganizationsForClientRow, error) {
	rows, err := q.db.Query(ctx, getConnectedOrganizationsForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConnectedOrganizationsForClientRow{}
	for rows.Next() {
		var i GetConnectedOrganizationsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TenantID,
			&i.Status,
			&i.CreatedAt,
			&i.ConnectedBy,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RemovedAt,
			&i.RemovedBy,
			&i.StatusReason,
			&i.TenantName,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.Country,
			&i.PostalCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionRequest = `-- name: GetConnectionRequest :one
SELECT id, client_id, tenant_id, status, created_at FROM connection_requests WHERE id = $1
`

func (q *Queries) GetConnectionRequest(ctx context.Context, id int64) (ConnectionRequest, error) {
	row := q.db.QueryRow(ctx, getConnectionRequest, id)
	var i ConnectionRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectionRequestsForClient = `-- name: GetConnectionRequestsForClient :many
SELECT cr.id, cr.client_id, cr.tenant_id, cr.status, cr.created_at, t.company_name as tenant_name
FROM connection_requests cr
JOIN tenants t ON cr.tenant_id = t.tenant_id
WHERE cr.client_id = $1
AND (NULLIF($2::text, '') IS NULL OR cr.status = $2)
ORDER BY cr.created_at DESC
LIMIT $4 OFFSET $3
`

type GetConnectionRequestsForClientParams struct {
	ClientID int64
	Column2  string
	Offset   int32
	Limit    int32
}

type GetConnectionRequestsForClientRow struct {
	ID         int64
	ClientID   int64
	TenantID   int64
	Status     string
	CreatedAt  time.Time
	TenantName *string
}

func (q *Queries) GetConnectionRequestsForClient(ctx context.Context, arg GetConnectionRequestsForClientParams) ([]GetConnectionRequestsForClientRow, error) {
	rows, err := q.db.Query(ctx, getConnectionRequestsForClient,
		arg.ClientID,
		arg.Column2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConnectionRequestsForClientRow{}
	for rows.Next() {
		var i GetConnectionRequestsForClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TenantID,
			&i.Status,
			&i.CreatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectionRequestsForTenant = `-- name: GetConnectionRequestsForTenant :many
SELECT cr.id, cr.client_id, cr.tenant_id, cr.status, cr.created_at, cp.connection_code, cp.full_name, cp.user_id, u.email, up.contact_number as phone
FROM connection_requests cr
JOIN client_profiles cp ON cr.client_id = cp.id
JOIN users u ON cp.user_id = u.id
LEFT JOIN user_profiles up ON u.id = up.user_id
WHERE cr.tenant_id = $1
AND (NULLIF($2::text, '') IS NULL OR cr.status = $2)
ORDER BY cr.created_at DESC
LIMIT $4 OFFSET $3
`

type GetConnectionRequestsForTenantParams struct {
	TenantID int64
	Column2  string
	Offset   int32
	Limit    int32
}

type GetConnectionRequestsForTenantRow struct {
	ID             int64
	ClientID       int64
	TenantID       int64
	Status         string
	CreatedAt      time.Time
	ConnectionCode string
	FullName       *string
	UserID         int64
	Email          string
	Phone          *string
}

func (q *Queries) GetConnectionRequestsForTenant(ctx context.Context, arg GetConnectionRequestsForTenantParams) ([]GetConnectionRequestsForTenantRow, error) {
	rows, err := q.db.Query(ctx, getConnectionRequestsForTenant,
		arg.TenantID,
		arg.Column2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConnectionRequestsForTenantRow{}
	for rows.Next() {
		var i GetConnectionRequestsForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TenantID,
			&i.Status,
			&i.CreatedAt,
			&i.ConnectionCode,
			&i.FullName,
			&i.UserID,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientConnectionStatus = `-- name: UpdateClientConnectionStatus :one
UPDATE client_connections
SET status = $2, removed_at = $3, removed_by = $4, status_reason = $5
WHERE id = $1
RETURNING id, client_id, tenant_id, status, created_at, connected_by, accepted_at, accepted_by, removed_at, removed_by, status_reason
`

type UpdateClientConnectionStatusParams struct {
	ID           int64
	Status       string
	RemovedAt    *time.Time
	RemovedBy    *int64
	StatusReason *string
}

func (q *Queries) UpdateClientConnectionStatus(ctx context.Context, arg UpdateClientConnectionStatusParams) (ClientConnection, error) {
	row := q.db.QueryRow(ctx, updateClientConnectionStatus,
		arg.ID,
		arg.Status,
		arg.RemovedAt,
		arg.RemovedBy,
		arg.StatusReason,
	)
	var i ClientConnection
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.ConnectedBy,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RemovedAt,
		&i.RemovedBy,
		&i.StatusReason,
	)
	return i, err
}

const updateConnectionRequestStatus = `-- name: UpdateConnectionRequestStatus :one
UPDATE connection_requests
SET status = $2
WHERE id = $1
RETURNING id, client_id, tenant_id, status, created_at
`

type UpdateConnectionRequestStatusParams struct {
	ID     int64
	Status string
}

func (q *Queries) UpdateConnectionRequestStatus(ctx context.Context, arg UpdateConnectionRequestStatusParams) (ConnectionRequest, error) {
	row := q.db.QueryRow(ctx, updateConnectionRequestStatus, arg.ID, arg.Status)
	var i ConnectionRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertConnectionPermissions = `-- name: UpsertConnectionPermissions :one
INSERT INTO connection_permissions (connection_id, view_profile, view_documents, upload_documents, create_applications, view_applications, approve_applications, manage_connection)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (connection_id)
DO UPDATE SET
    view_profile = EXCLUDED.view_profile,
    view_documents = EXCLUDED.view_documents,
    upload_documents = EXCLUDED.upload_documents,
    create_applications = EXCLUDED.create_applications,
    view_applications = EXCLUDED.view_applications,
    approve_applications = EXCLUDED.approve_applications,
    manage_connection = EXCLUDED.manage_connection,
    updated_at = now()
RETURNING id, connection_id, view_profile, view_documents, upload_documents, create_applications, view_applications, approve_applications, manage_connection, updated_at
`

type UpsertConnectionPermissionsParams struct {
	ConnectionID        int64
	ViewProfile         bool
	ViewDocuments       bool
	UploadDocuments     bool
	CreateApplications  bool
	ViewApplications    bool
	ApproveApplications bool
	ManageConnection    bool
}

func (q *Queries) UpsertConnectionPermissions(ctx context.Context, arg UpsertConnectionPermissionsParams) (ConnectionPermission, error) {
	row := q.db.QueryRow(ctx, upsertConnectionPermissions,
		arg.ConnectionID,
		arg.ViewProfile,
		arg.ViewDocuments,
		arg.UploadDocuments,
		arg.CreateApplications,
		arg.ViewApplications,
		arg.ApproveApplications,
		arg.ManageConnection,
	)
	var i ConnectionPermission
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.ViewProfile,
		&i.ViewDocuments,
		&i.UploadDocuments,
		&i.CreateApplications,
		&i.ViewApplications,
		&i.ApproveApplications,
		&i.ManageConnection,
		&i.UpdatedAt,
	)
	return i, err
}
