// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kyc.sql

package public

import (
	"context"
)

const deleteTenantDocumentsByType = `-- name: DeleteTenantDocumentsByType :exec
DELETE FROM tenant_documents
WHERE tenant_id = $1 AND document_type = $2
`

type DeleteTenantDocumentsByTypeParams struct {
	TenantID     int64
	DocumentType string
}

func (q *Queries) DeleteTenantDocumentsByType(ctx context.Context, arg DeleteTenantDocumentsByTypeParams) error {
	_, err := q.db.Exec(ctx, deleteTenantDocumentsByType, arg.TenantID, arg.DocumentType)
	return err
}

const getTenantDocuments = `-- name: GetTenantDocuments :many
SELECT id, tenant_id, document_type, original_name, stored_name, mime_type, storage_path, uploaded_at, uploaded_by FROM tenant_documents
WHERE tenant_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) GetTenantDocuments(ctx context.Context, tenantID int64) ([]TenantDocument, error) {
	rows, err := q.db.Query(ctx, getTenantDocuments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantDocument{}
	for rows.Next() {
		var i TenantDocument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentType,
			&i.OriginalName,
			&i.StoredName,
			&i.MimeType,
			&i.StoragePath,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTenantDocument = `-- name: InsertTenantDocument :one
INSERT INTO tenant_documents (tenant_id, document_type, original_name, stored_name, mime_type, storage_path, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, document_type, original_name, stored_name, mime_type, storage_path, uploaded_at, uploaded_by
`

type InsertTenantDocumentParams struct {
	TenantID     int64
	DocumentType string
	OriginalName string
	StoredName   string
	MimeType     string
	StoragePath  string
	UploadedBy   int64
}

func (q *Queries) InsertTenantDocument(ctx context.Context, arg InsertTenantDocumentParams) (TenantDocument, error) {
	row := q.db.QueryRow(ctx, insertTenantDocument,
		arg.TenantID,
		arg.DocumentType,
		arg.OriginalName,
		arg.StoredName,
		arg.MimeType,
		arg.StoragePath,
		arg.UploadedBy,
	)
	var i TenantDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentType,
		&i.OriginalName,
		&i.StoredName,
		&i.MimeType,
		&i.StoragePath,
		&i.UploadedAt,
		&i.UploadedBy,
	)
	return i, err
}

const rejectTenantKYC = `-- name: RejectTenantKYC :exec
UPDATE tenants
SET kyc_status = 'REJECTED',
    kyc_rejected_by = $1,
    kyc_rejected_at = now(),
    kyc_rejection_reason = $2
WHERE tenant_id = $3
`

type RejectTenantKYCParams struct {
	RejectedBy *int64
	Reason     *string
	TenantID   int64
}

func (q *Queries) RejectTenantKYC(ctx context.Context, arg RejectTenantKYCParams) error {
	_, err := q.db.Exec(ctx, rejectTenantKYC, arg.RejectedBy, arg.Reason, arg.TenantID)
	return err
}

const updateTenantKYCStatus = `-- name: UpdateTenantKYCStatus :exec
UPDATE tenants
SET kyc_status = $1
WHERE tenant_id = $2
`

type UpdateTenantKYCStatusParams struct {
	Status   string
	TenantID int64
}

func (q *Queries) UpdateTenantKYCStatus(ctx context.Context, arg UpdateTenantKYCStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantKYCStatus, arg.Status, arg.TenantID)
	return err
}

const verifyTenantKYC = `-- name: VerifyTenantKYC :exec
UPDATE tenants
SET kyc_status = 'VERIFIED',
    kyc_verified_by = $1,
    kyc_verified_at = now()
WHERE tenant_id = $2
`

type VerifyTenantKYCParams struct {
	VerifiedBy *int64
	TenantID   int64
}

func (q *Queries) VerifyTenantKYC(ctx context.Context, arg VerifyTenantKYCParams) error {
	_, err := q.db.Exec(ctx, verifyTenantKYC, arg.VerifiedBy, arg.TenantID)
	return err
}
