// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_links.sql

package public

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (
    token, tenant_id, application_id, client_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, token, tenant_id, application_id, client_id, expires_at, is_used, created_at
`

type CreateMagicLinkParams struct {
	Token         uuid.UUID
	TenantID      int64
	ApplicationID int64
	ClientID      int64
	ExpiresAt     time.Time
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink,
		arg.Token,
		arg.TenantID,
		arg.ApplicationID,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TenantID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT id, token, tenant_id, application_id, client_id, expires_at, is_used, created_at FROM magic_links
WHERE token = $1
`

func (q *Queries) GetMagicLinkByToken(ctx context.Context, token uuid.UUID) (MagicLink, error) {
	row := q.db.QueryRow(ctx, getMagicLinkByToken, token)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TenantID,
		&i.ApplicationID,
		&i.ClientID,
		&i.ExpiresAt,
		&i.IsUsed,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateMagicLinksForApplication = `-- name: InvalidateMagicLinksForApplication :exec
UPDATE magic_links
SET is_used = TRUE
WHERE application_id = $1 AND tenant_id = $2
`

type InvalidateMagicLinksForApplicationParams struct {
	ApplicationID int64
	TenantID      int64
}

func (q *Queries) InvalidateMagicLinksForApplication(ctx context.Context, arg InvalidateMagicLinksForApplicationParams) error {
	_, err := q.db.Exec(ctx, invalidateMagicLinksForApplication, arg.ApplicationID, arg.TenantID)
	return err
}

const markMagicLinkAsUsed = `-- name: MarkMagicLinkAsUsed :exec
UPDATE magic_links
SET is_used = TRUE
WHERE token = $1
`

func (q *Queries) MarkMagicLinkAsUsed(ctx context.Context, token uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMagicLinkAsUsed, token)
	return err
}
