// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package public

import (
	"context"
	"time"
)

const addUserToTenant = `-- name: AddUserToTenant :one
INSERT INTO user_tenants (user_id, tenant_id, role_id, status, is_owner, joined_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, tenant_id) DO UPDATE
   SET role_id = EXCLUDED.role_id, status = EXCLUDED.status, is_owner = EXCLUDED.is_owner
RETURNING id, user_id, tenant_id, role_id, status, is_owner, joined_at, created_at
`

type AddUserToTenantParams struct {
	UserID   int64
	TenantID int64
	RoleID   *int64
	Status   string
	IsOwner  bool
}

func (q *Queries) AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (UserTenant, error) {
	row := q.db.QueryRow(ctx, addUserToTenant,
		arg.UserID,
		arg.TenantID,
		arg.RoleID,
		arg.Status,
		arg.IsOwner,
	)
	var i UserTenant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleID,
		&i.Status,
		&i.IsOwner,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT ut.id, ut.user_id, ut.tenant_id, ut.role_id, ut.status, ut.is_owner, ut.joined_at, ut.created_at, COALESCE(r.role_name, '') AS role_name
FROM user_tenants ut
LEFT JOIN roles r ON r.role_id = ut.role_id
WHERE ut.user_id = $1 AND ut.tenant_id = $2
`

type GetMembershipParams struct {
	UserID   int64
	TenantID int64
}

type GetMembershipRow struct {
	ID        int64
	UserID    int64
	TenantID  int64
	RoleID    *int64
	Status    string
	IsOwner   bool
	JoinedAt  *time.Time
	CreatedAt time.Time
	RoleName  string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.TenantID)
	var i GetMembershipRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RoleID,
		&i.Status,
		&i.IsOwner,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.RoleName,
	)
	return i, err
}

const listUserTenantsForSelection = `-- name: ListUserTenantsForSelection :many
SELECT t.tenant_id, t.tenant_name, COALESCE(r.role_name, '') AS role,
       (ut.status = 'Active' AND t.is_active) AS is_active
FROM user_tenants ut
JOIN tenants t ON t.tenant_id = ut.tenant_id
LEFT JOIN roles r ON r.role_id = ut.role_id
WHERE ut.user_id = $1
ORDER BY t.tenant_name ASC
`

type ListUserTenantsForSelectionRow struct {
	TenantID   int64
	TenantName string
	Role       string
	IsActive   *bool
}

func (q *Queries) ListUserTenantsForSelection(ctx context.Context, userID int64) ([]ListUserTenantsForSelectionRow, error) {
	rows, err := q.db.Query(ctx, listUserTenantsForSelection, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTenantsForSelectionRow{}
	for rows.Next() {
		var i ListUserTenantsForSelectionRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.Role,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTenant = `-- name: RemoveUserFromTenant :execrows
DELETE FROM user_tenants WHERE user_id = $1 AND tenant_id = $2
`

type RemoveUserFromTenantParams struct {
	UserID   int64
	TenantID int64
}

func (q *Queries) RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeUserFromTenant, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMembership = `-- name: UpdateMembership :exec
UPDATE user_tenants
SET role_id = $1, status = $2
WHERE user_id = $3 AND tenant_id = $4
`

type UpdateMembershipParams struct {
	RoleID   *int64
	Status   string
	UserID   int64
	TenantID int64
}

func (q *Queries) UpdateMembership(ctx context.Context, arg UpdateMembershipParams) error {
	_, err := q.db.Exec(ctx, updateMembership,
		arg.RoleID,
		arg.Status,
		arg.UserID,
		arg.TenantID,
	)
	return err
}
