// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package public

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID         int64
	UserID     int64
	TokenHash  string
	Purpose    string
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type CompanyProfile struct {
	TenantID       int64
	CompanyName    *string
	CompanyLogoUrl *string
	ContactEmail   *string
	ContactPhone   *string
	SupportPhone   *string
	Website        *string
	AddressLine1   *string
	AddressLine2   *string
	City           *string
	State          *string
	Country        *string
	PostalCode     *string
	Gstin          *string
	Pan            *string
	CinNo          *string
	MsmeNo         *string
	UpdatedAt      time.Time
}

type Notification struct {
	ID        int64
	UserID    int64
	TenantID  *int64
	Title     *string
	Body      *string
	Type      *string
	Link      *string
	IsRead    bool
	CreatedAt time.Time
}

type OtpCode struct {
	ID         int64
	Email      string
	CodeHash   string
	Purpose    string
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt *time.Time
	CreatedAt  time.Time
}

type Page struct {
	PageID        int64
	PageName      string
	RouteUrl      string
	PermissionKey *string
	DisplayOrder  int32
	ParentPageID  *int64
}

type PromoCode struct {
	PromoID       int64
	Code          string
	DiscountType  string
	DiscountValue pgtype.Numeric
	ExtensionDays int32
	MaxUses       *int32
	UsedCount     int32
	ValidFrom     *time.Time
	ValidTo       *time.Time
	IsActive      bool
	CreatedAt     time.Time
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	TenantID  *int64
	TokenHash string
	UserAgent *string
	IpAddress *string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type Role struct {
	RoleID    int64
	RoleName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RolePagePermission struct {
	ID        int64
	RoleID    int64
	PageID    int64
	CanView   bool
	CanAdd    bool
	CanEdit   bool
	CanDelete bool
}

type SubscriptionPlan struct {
	PlanID          int64
	PlanName        string
	Code            *string
	Price           pgtype.Numeric
	DurationMonths  int32
	DurationDays    int32
	MaxUsers        *int32
	MaxStudents     *int32
	WhatsappCredits int32
	FeaturesJson    []byte
	IsTrial         bool
	IsActive        bool
	Status          string
	CreatedAt       time.Time
}

type SupportTicket struct {
	TicketID      int64
	TenantID      int64
	UserID        int64
	Subject       string
	Category      *string
	Priority      *string
	Description   *string
	AttachmentUrl *string
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type SystemLog struct {
	LogID      int64
	LogDate    time.Time
	LogLevel   string
	Source     *string
	Message    *string
	StackTrace *string
	TenantName *string
	UserID     *string
	RequestUrl *string
	IpAddress  *string
}

type Tenant struct {
	TenantID          int64
	TenantName        string
	CompanyName       *string
	TenantCode        *string
	SchemaName        string
	Subdomain         *string
	Status            string
	ContactEmail      *string
	ContactPhone      *string
	LogoUrl           *string
	WhatsappBalance   *int32
	WhatsappSentCount int64
	IsActive          bool
	CreatedBy         *int64
	UpdatedBy         *int64
	CreatedAt         time.Time
	UpdatedAt         *time.Time
}

type TenantPayment struct {
	PaymentID       int64
	TenantID        int64
	PlanID          *int64
	PromoCodeID     *int64
	OriginalAmount  pgtype.Numeric
	DiscountAmount  pgtype.Numeric
	FinalAmount     pgtype.Numeric
	PaymentMode     *string
	ReferenceNumber *string
	CreatedAt       time.Time
}

type TenantSubscription struct {
	SubscriptionID int64
	TenantID       int64
	PlanID         int64
	StartDate      time.Time
	EndDate        time.Time
	Status         string
	CreatedAt      time.Time
}

type TicketMessage struct {
	ID            int64
	TicketID      int64
	SenderUserID  int64
	IsAdminReply  bool
	Message       string
	AttachmentUrl *string
	CreatedOn     time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash *string
	GoogleID     *string
	IsActive     bool
	IsVerified   bool
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type UserActivity struct {
	ID          int64
	UserID      string
	UserName    *string
	TenantID    *int64
	Url         string
	Method      string
	IpAddress   *string
	Description *string
	Changes     *string
	CreatedOn   time.Time
	BranchID    *uuid.UUID
}

type UserPermission struct {
	ID       int64
	UserID   int64
	TenantID int64
	PageID   int64
	CanView  bool
}

type UserProfile struct {
	UserID        int64
	FirstName     *string
	LastName      *string
	JobTitle      *string
	ContactNumber *string
	UpdatedAt     time.Time
}

type UserTenant struct {
	ID        int64
	UserID    int64
	TenantID  int64
	RoleID    *int64
	Status    string
	IsOwner   bool
	JoinedAt  *time.Time
	CreatedAt time.Time
}
