// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_types.sql

package public

import (
	"context"
)

const createOrganizationType = `-- name: CreateOrganizationType :one
INSERT INTO organization_types (
    name, description
) VALUES (
    $1, $2
) RETURNING id, name, description, is_active, created_at, updated_at
`

type CreateOrganizationTypeParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateOrganizationType(ctx context.Context, arg CreateOrganizationTypeParams) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, createOrganizationType, arg.Name, arg.Description)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganizationType = `-- name: DeleteOrganizationType :exec
UPDATE organization_types
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeleteOrganizationType(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrganizationType, id)
	return err
}

const getOrganizationType = `-- name: GetOrganizationType :one
SELECT id, name, description, is_active, created_at, updated_at FROM organization_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationType(ctx context.Context, id int64) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, getOrganizationType, id)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationTypes = `-- name: ListOrganizationTypes :many
SELECT id, name, description, is_active, created_at, updated_at FROM organization_types
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListOrganizationTypes(ctx context.Context) ([]OrganizationType, error) {
	rows, err := q.db.Query(ctx, listOrganizationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationType{}
	for rows.Next() {
		var i OrganizationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationType = `-- name: UpdateOrganizationType :one
UPDATE organization_types
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_active, created_at, updated_at
`

type UpdateOrganizationTypeParams struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) UpdateOrganizationType(ctx context.Context, arg UpdateOrganizationTypeParams) (OrganizationType, error) {
	row := q.db.QueryRow(ctx, updateOrganizationType, arg.ID, arg.Name, arg.Description)
	var i OrganizationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
