// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package public

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupSystemLogs = `-- name: CleanupSystemLogs :execrows
DELETE FROM system_logs WHERE log_date < (now() - make_interval(days => $1::int))
`

func (q *Queries) CleanupSystemLogs(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupSystemLogs, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSystemLogs = `-- name: CountSystemLogs :one
SELECT count(*) FROM system_logs
WHERE ($1::text = '' OR message ILIKE '%'||$1||'%' OR source ILIKE '%'||$1||'%' OR log_level ILIKE '%'||$1||'%')
  AND ($2::timestamptz IS NULL OR log_date >= $2)
  AND ($3::timestamptz IS NULL OR log_date <= $3)
`

type CountSystemLogsParams struct {
	Filter   string
	FromDate *time.Time
	ToDate   *time.Time
}

func (q *Queries) CountSystemLogs(ctx context.Context, arg CountSystemLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemLogs, arg.Filter, arg.FromDate, arg.ToDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserActivities = `-- name: CountUserActivities :one
SELECT count(*) FROM user_activities
WHERE tenant_id = $1 AND branch_id = $2
`

type CountUserActivitiesParams struct {
	TenantID *int64
	BranchID *uuid.UUID
}

func (q *Queries) CountUserActivities(ctx context.Context, arg CountUserActivitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserActivities, arg.TenantID, arg.BranchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, tenant_id, title, body, type, link)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tenant_id, title, body, type, link, is_read, created_at
`

type CreateNotificationParams struct {
	UserID   int64
	TenantID *int64
	Title    *string
	Body     *string
	Type     *string
	Link     *string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.TenantID,
		arg.Title,
		arg.Body,
		arg.Type,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Title,
		&i.Body,
		&i.Type,
		&i.Link,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSystemLog = `-- name: DeleteSystemLog :execrows
DELETE FROM system_logs WHERE log_id = $1
`

func (q *Queries) DeleteSystemLog(ctx context.Context, logID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSystemLog, logID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSystemLog = `-- name: GetSystemLog :one
SELECT log_id, log_date, log_level, source, message, stack_trace, tenant_name, user_id, request_url, ip_address FROM system_logs WHERE log_id = $1
`

func (q *Queries) GetSystemLog(ctx context.Context, logID int64) (SystemLog, error) {
	row := q.db.QueryRow(ctx, getSystemLog, logID)
	var i SystemLog
	err := row.Scan(
		&i.LogID,
		&i.LogDate,
		&i.LogLevel,
		&i.Source,
		&i.Message,
		&i.StackTrace,
		&i.TenantName,
		&i.UserID,
		&i.RequestUrl,
		&i.IpAddress,
	)
	return i, err
}

const insertSystemLog = `-- name: InsertSystemLog :exec
INSERT INTO system_logs (log_level, source, message, stack_trace, tenant_name, user_id, request_url, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSystemLogParams struct {
	LogLevel   string
	Source     *string
	Message    *string
	StackTrace *string
	TenantName *string
	UserID     *string
	RequestUrl *string
	IpAddress  *string
}

func (q *Queries) InsertSystemLog(ctx context.Context, arg InsertSystemLogParams) error {
	_, err := q.db.Exec(ctx, insertSystemLog,
		arg.LogLevel,
		arg.Source,
		arg.Message,
		arg.StackTrace,
		arg.TenantName,
		arg.UserID,
		arg.RequestUrl,
		arg.IpAddress,
	)
	return err
}

const insertUserActivity = `-- name: InsertUserActivity :exec
INSERT INTO user_activities (user_id, user_name, tenant_id, url, method, ip_address, description, changes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertUserActivityParams struct {
	UserID      string
	UserName    *string
	TenantID    *int64
	Url         string
	Method      string
	IpAddress   *string
	Description *string
	Changes     *string
}

func (q *Queries) InsertUserActivity(ctx context.Context, arg InsertUserActivityParams) error {
	_, err := q.db.Exec(ctx, insertUserActivity,
		arg.UserID,
		arg.UserName,
		arg.TenantID,
		arg.Url,
		arg.Method,
		arg.IpAddress,
		arg.Description,
		arg.Changes,
	)
	return err
}

const listRecentUserActivities = `-- name: ListRecentUserActivities :many
SELECT id, user_id, user_name, tenant_id, url, method, ip_address, description, changes, created_on, branch_id FROM user_activities
WHERE tenant_id = $1 AND branch_id = $2
ORDER BY created_on DESC
LIMIT $4 OFFSET $3
`

type ListRecentUserActivitiesParams struct {
	TenantID *int64
	BranchID *uuid.UUID
	Off      int32
	Lim      int32
}

// ── User activity audit ─────────────────────────────────────────────────
func (q *Queries) ListRecentUserActivities(ctx context.Context, arg ListRecentUserActivitiesParams) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, listRecentUserActivities,
		arg.TenantID,
		arg.BranchID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivity{}
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.TenantID,
			&i.Url,
			&i.Method,
			&i.IpAddress,
			&i.Description,
			&i.Changes,
			&i.CreatedOn,
			&i.BranchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemLogs = `-- name: ListSystemLogs :many
SELECT log_id, log_date, log_level, source, message, stack_trace, tenant_name, user_id, request_url, ip_address FROM system_logs
WHERE ($1::text = '' OR message ILIKE '%'||$1||'%' OR source ILIKE '%'||$1||'%' OR log_level ILIKE '%'||$1||'%')
  AND ($2::timestamptz IS NULL OR log_date >= $2)
  AND ($3::timestamptz IS NULL OR log_date <= $3)
ORDER BY log_date DESC
LIMIT $5 OFFSET $4
`

type ListSystemLogsParams struct {
	Filter   string
	FromDate *time.Time
	ToDate   *time.Time
	Off      int32
	Lim      int32
}

// ── System logs ─────────────────────────────────────────────────────────
func (q *Queries) ListSystemLogs(ctx context.Context, arg ListSystemLogsParams) ([]SystemLog, error) {
	rows, err := q.db.Query(ctx, listSystemLogs,
		arg.Filter,
		arg.FromDate,
		arg.ToDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemLog{}
	for rows.Next() {
		var i SystemLog
		if err := rows.Scan(
			&i.LogID,
			&i.LogDate,
			&i.LogLevel,
			&i.Source,
			&i.Message,
			&i.StackTrace,
			&i.TenantName,
			&i.UserID,
			&i.RequestUrl,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, tenant_id, title, body, type, link, is_read, created_at FROM notifications WHERE user_id = $1 AND is_read = FALSE ORDER BY created_at DESC
`

// ── Notifications ───────────────────────────────────────────────────────
func (q *Queries) ListUnreadNotifications(ctx context.Context, userID int64) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.Title,
			&i.Body,
			&i.Type,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = TRUE WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
