// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package public

import (
	"context"
)

const getCompanyProfile = `-- name: GetCompanyProfile :one
SELECT tenant_id, company_name, company_logo_url, contact_email, contact_phone, support_phone, website, address_line1, address_line2, city, state, country, postal_code, gstin, pan, cin_no, msme_no, updated_at FROM company_profiles WHERE tenant_id = $1
`

func (q *Queries) GetCompanyProfile(ctx context.Context, tenantID int64) (CompanyProfile, error) {
	row := q.db.QueryRow(ctx, getCompanyProfile, tenantID)
	var i CompanyProfile
	err := row.Scan(
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.SupportPhone,
		&i.Website,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Gstin,
		&i.Pan,
		&i.CinNo,
		&i.MsmeNo,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicTenantLogo = `-- name: GetPublicTenantLogo :one
SELECT COALESCE(cp.company_logo_url, t.logo_url) AS logo_url, COALESCE(cp.company_name, t.company_name, t.tenant_name) AS company_name
FROM tenants t
LEFT JOIN company_profiles cp ON cp.tenant_id = t.tenant_id
WHERE t.tenant_id = $1
`

type GetPublicTenantLogoRow struct {
	LogoUrl     *string
	CompanyName string
}

func (q *Queries) GetPublicTenantLogo(ctx context.Context, tenantID int64) (GetPublicTenantLogoRow, error) {
	row := q.db.QueryRow(ctx, getPublicTenantLogo, tenantID)
	var i GetPublicTenantLogoRow
	err := row.Scan(&i.LogoUrl, &i.CompanyName)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, first_name, last_name, job_title, contact_number, updated_at FROM user_profiles WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID int64) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.ContactNumber,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCompanyProfile = `-- name: UpsertCompanyProfile :one
INSERT INTO company_profiles (
    tenant_id, company_name, company_logo_url, contact_email, contact_phone, support_phone,
    website, address_line1, address_line2, city, state, country, postal_code, gstin, pan, cin_no, msme_no
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (tenant_id) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_logo_url = EXCLUDED.company_logo_url,
    contact_email = EXCLUDED.contact_email,
    contact_phone = EXCLUDED.contact_phone,
    support_phone = EXCLUDED.support_phone,
    website = EXCLUDED.website,
    address_line1 = EXCLUDED.address_line1,
    address_line2 = EXCLUDED.address_line2,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    postal_code = EXCLUDED.postal_code,
    gstin = EXCLUDED.gstin,
    pan = EXCLUDED.pan,
    cin_no = EXCLUDED.cin_no,
    msme_no = EXCLUDED.msme_no,
    updated_at = now()
RETURNING tenant_id, company_name, company_logo_url, contact_email, contact_phone, support_phone, website, address_line1, address_line2, city, state, country, postal_code, gstin, pan, cin_no, msme_no, updated_at
`

type UpsertCompanyProfileParams struct {
	TenantID       int64
	CompanyName    *string
	CompanyLogoUrl *string
	ContactEmail   *string
	ContactPhone   *string
	SupportPhone   *string
	Website        *string
	AddressLine1   *string
	AddressLine2   *string
	City           *string
	State          *string
	Country        *string
	PostalCode     *string
	Gstin          *string
	Pan            *string
	CinNo          *string
	MsmeNo         *string
}

func (q *Queries) UpsertCompanyProfile(ctx context.Context, arg UpsertCompanyProfileParams) (CompanyProfile, error) {
	row := q.db.QueryRow(ctx, upsertCompanyProfile,
		arg.TenantID,
		arg.CompanyName,
		arg.CompanyLogoUrl,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.SupportPhone,
		arg.Website,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.Gstin,
		arg.Pan,
		arg.CinNo,
		arg.MsmeNo,
	)
	var i CompanyProfile
	err := row.Scan(
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.SupportPhone,
		&i.Website,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.Gstin,
		&i.Pan,
		&i.CinNo,
		&i.MsmeNo,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, first_name, last_name, job_title, contact_number)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    job_title = EXCLUDED.job_title,
    contact_number = EXCLUDED.contact_number,
    updated_at = now()
RETURNING user_id, first_name, last_name, job_title, contact_number, updated_at
`

type UpsertUserProfileParams struct {
	UserID        int64
	FirstName     *string
	LastName      *string
	JobTitle      *string
	ContactNumber *string
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.JobTitle,
		arg.ContactNumber,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.JobTitle,
		&i.ContactNumber,
		&i.UpdatedAt,
	)
	return i, err
}
