// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package public

import (
	"context"
)

const ensureRole = `-- name: EnsureRole :one
INSERT INTO roles (role_name) VALUES ($1)
ON CONFLICT (lower(role_name)) DO UPDATE SET updated_at = now()
RETURNING role_id, role_name, created_at, updated_at
`

func (q *Queries) EnsureRole(ctx context.Context, roleName string) (Role, error) {
	row := q.db.QueryRow(ctx, ensureRole, roleName)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, created_at, updated_at FROM roles WHERE role_id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id, role_name, created_at, updated_at FROM roles WHERE lower(role_name) = lower($1)
`

func (q *Queries) GetRoleByName(ctx context.Context, lower string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, lower)
	var i Role
	err := row.Scan(
		&i.RoleID,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAllowedPageUrls = `-- name: GetUserAllowedPageUrls :many
SELECT DISTINCT p.route_url
FROM pages p
WHERE p.page_id IN (
    -- role-derived view grants for the user's role in this tenant
    SELECT rpp.page_id
    FROM role_page_permissions rpp
    JOIN user_tenants ut ON ut.role_id = rpp.role_id
    WHERE ut.user_id = $1 AND ut.tenant_id = $2 AND rpp.can_view
    UNION
    -- per-user overrides
    SELECT up.page_id
    FROM user_permissions up
    WHERE up.user_id = $1 AND up.tenant_id = $2 AND up.can_view
)
ORDER BY p.route_url
`

type GetUserAllowedPageUrlsParams struct {
	UserID   int64
	TenantID int64
}

func (q *Queries) GetUserAllowedPageUrls(ctx context.Context, arg GetUserAllowedPageUrlsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserAllowedPageUrls, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var route_url string
		if err := rows.Scan(&route_url); err != nil {
			return nil, err
		}
		items = append(items, route_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPagePermissions = `-- name: GetUserPagePermissions :many
SELECT 
    p.route_url,
    COALESCE(rpp.can_view, false) AS can_view,
    COALESCE(rpp.can_add, false) AS can_add,
    COALESCE(rpp.can_edit, false) AS can_edit,
    COALESCE(rpp.can_delete, false) AS can_delete
FROM pages p
JOIN role_page_permissions rpp ON rpp.page_id = p.page_id
JOIN user_tenants ut ON ut.role_id = rpp.role_id
WHERE ut.user_id = $1 AND ut.tenant_id = $2
`

type GetUserPagePermissionsParams struct {
	UserID   int64
	TenantID int64
}

type GetUserPagePermissionsRow struct {
	RouteUrl  string
	CanView   bool
	CanAdd    bool
	CanEdit   bool
	CanDelete bool
}

func (q *Queries) GetUserPagePermissions(ctx context.Context, arg GetUserPagePermissionsParams) ([]GetUserPagePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPagePermissions, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPagePermissionsRow{}
	for rows.Next() {
		var i GetUserPagePermissionsRow
		if err := rows.Scan(
			&i.RouteUrl,
			&i.CanView,
			&i.CanAdd,
			&i.CanEdit,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantUserPagePermission = `-- name: GrantUserPagePermission :exec
INSERT INTO user_permissions (user_id, tenant_id, page_id, can_view)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, tenant_id, page_id) DO UPDATE SET can_view = EXCLUDED.can_view
`

type GrantUserPagePermissionParams struct {
	UserID   int64
	TenantID int64
	PageID   int64
	CanView  bool
}

func (q *Queries) GrantUserPagePermission(ctx context.Context, arg GrantUserPagePermissionParams) error {
	_, err := q.db.Exec(ctx, grantUserPagePermission,
		arg.UserID,
		arg.TenantID,
		arg.PageID,
		arg.CanView,
	)
	return err
}

const listPages = `-- name: ListPages :many
SELECT page_id, page_name, route_url, permission_key, display_order, parent_page_id FROM pages ORDER BY display_order ASC, page_name ASC
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.PageID,
			&i.PageName,
			&i.RouteUrl,
			&i.PermissionKey,
			&i.DisplayOrder,
			&i.ParentPageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePagePermissions = `-- name: ListRolePagePermissions :many
SELECT id, role_id, page_id, can_view, can_add, can_edit, can_delete FROM role_page_permissions
`

func (q *Queries) ListRolePagePermissions(ctx context.Context) ([]RolePagePermission, error) {
	rows, err := q.db.Query(ctx, listRolePagePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RolePagePermission{}
	for rows.Next() {
		var i RolePagePermission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.PageID,
			&i.CanView,
			&i.CanAdd,
			&i.CanEdit,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT role_id, role_name, created_at, updated_at FROM roles ORDER BY role_name ASC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRolePagePermission = `-- name: UpsertRolePagePermission :exec
INSERT INTO role_page_permissions (role_id, page_id, can_view, can_add, can_edit, can_delete)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (role_id, page_id) DO UPDATE SET
    can_view = EXCLUDED.can_view,
    can_add = EXCLUDED.can_add,
    can_edit = EXCLUDED.can_edit,
    can_delete = EXCLUDED.can_delete
`

type UpsertRolePagePermissionParams struct {
	RoleID    int64
	PageID    int64
	CanView   bool
	CanAdd    bool
	CanEdit   bool
	CanDelete bool
}

func (q *Queries) UpsertRolePagePermission(ctx context.Context, arg UpsertRolePagePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertRolePagePermission,
		arg.RoleID,
		arg.PageID,
		arg.CanView,
		arg.CanAdd,
		arg.CanEdit,
		arg.CanDelete,
	)
	return err
}
