// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package public

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPromo = `-- name: CreatePromo :one
INSERT INTO promo_codes (code, discount_type, discount_value, extension_days, max_uses, valid_from, valid_to, is_active)
VALUES (upper($1), $2, $3, $4, $5, $6, $7, $8)
RETURNING promo_id, code, discount_type, discount_value, extension_days, max_uses, used_count, valid_from, valid_to, is_active, created_at
`

type CreatePromoParams struct {
	Code          interface{}
	DiscountType  string
	DiscountValue pgtype.Numeric
	ExtensionDays int32
	MaxUses       *int32
	ValidFrom     *time.Time
	ValidTo       *time.Time
	IsActive      bool
}

func (q *Queries) CreatePromo(ctx context.Context, arg CreatePromoParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromo,
		arg.Code,
		arg.DiscountType,
		arg.DiscountValue,
		arg.ExtensionDays,
		arg.MaxUses,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
	)
	var i PromoCode
	err := row.Scan(
		&i.PromoID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.ExtensionDays,
		&i.MaxUses,
		&i.UsedCount,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantPayment = `-- name: CreateTenantPayment :one
INSERT INTO tenant_payments (tenant_id, plan_id, promo_code_id, original_amount, discount_amount, final_amount, payment_mode, reference_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING payment_id, tenant_id, plan_id, promo_code_id, original_amount, discount_amount, final_amount, payment_mode, reference_number, created_at
`

type CreateTenantPaymentParams struct {
	TenantID        int64
	PlanID          *int64
	PromoCodeID     *int64
	OriginalAmount  pgtype.Numeric
	DiscountAmount  pgtype.Numeric
	FinalAmount     pgtype.Numeric
	PaymentMode     *string
	ReferenceNumber *string
}

func (q *Queries) CreateTenantPayment(ctx context.Context, arg CreateTenantPaymentParams) (TenantPayment, error) {
	row := q.db.QueryRow(ctx, createTenantPayment,
		arg.TenantID,
		arg.PlanID,
		arg.PromoCodeID,
		arg.OriginalAmount,
		arg.DiscountAmount,
		arg.FinalAmount,
		arg.PaymentMode,
		arg.ReferenceNumber,
	)
	var i TenantPayment
	err := row.Scan(
		&i.PaymentID,
		&i.TenantID,
		&i.PlanID,
		&i.PromoCodeID,
		&i.OriginalAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.PaymentMode,
		&i.ReferenceNumber,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantSubscription = `-- name: CreateTenantSubscription :one
INSERT INTO tenant_subscriptions (tenant_id, plan_id, start_date, end_date, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING subscription_id, tenant_id, plan_id, start_date, end_date, status, created_at
`

type CreateTenantSubscriptionParams struct {
	TenantID  int64
	PlanID    int64
	StartDate time.Time
	EndDate   time.Time
	Status    string
}

func (q *Queries) CreateTenantSubscription(ctx context.Context, arg CreateTenantSubscriptionParams) (TenantSubscription, error) {
	row := q.db.QueryRow(ctx, createTenantSubscription,
		arg.TenantID,
		arg.PlanID,
		arg.StartDate,
		arg.EndDate,
		arg.Status,
	)
	var i TenantSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.TenantID,
		&i.PlanID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentSubscription = `-- name: GetCurrentSubscription :one
SELECT subscription_id, tenant_id, plan_id, start_date, end_date, status, created_at FROM tenant_subscriptions
WHERE tenant_id = $1
ORDER BY end_date DESC
LIMIT 1
`

func (q *Queries) GetCurrentSubscription(ctx context.Context, tenantID int64) (TenantSubscription, error) {
	row := q.db.QueryRow(ctx, getCurrentSubscription, tenantID)
	var i TenantSubscription
	err := row.Scan(
		&i.SubscriptionID,
		&i.TenantID,
		&i.PlanID,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT plan_id, plan_name, code, price, duration_months, duration_days, max_users, max_students, whatsapp_credits, features_json, is_trial, is_active, status, created_at FROM subscription_plans WHERE plan_id = $1
`

func (q *Queries) GetPlan(ctx context.Context, planID int64) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, planID)
	var i SubscriptionPlan
	err := row.Scan(
		&i.PlanID,
		&i.PlanName,
		&i.Code,
		&i.Price,
		&i.DurationMonths,
		&i.DurationDays,
		&i.MaxUsers,
		&i.MaxStudents,
		&i.WhatsappCredits,
		&i.FeaturesJson,
		&i.IsTrial,
		&i.IsActive,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPromoByCode = `-- name: GetPromoByCode :one
SELECT promo_id, code, discount_type, discount_value, extension_days, max_uses, used_count, valid_from, valid_to, is_active, created_at FROM promo_codes WHERE upper(code) = upper($1)
`

func (q *Queries) GetPromoByCode(ctx context.Context, upper interface{}) (PromoCode, error) {
	row := q.db.QueryRow(ctx, getPromoByCode, upper)
	var i PromoCode
	err := row.Scan(
		&i.PromoID,
		&i.Code,
		&i.DiscountType,
		&i.DiscountValue,
		&i.ExtensionDays,
		&i.MaxUses,
		&i.UsedCount,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPromoUse = `-- name: IncrementPromoUse :exec
UPDATE promo_codes SET used_count = used_count + 1 WHERE promo_id = $1
`

func (q *Queries) IncrementPromoUse(ctx context.Context, promoID int64) error {
	_, err := q.db.Exec(ctx, incrementPromoUse, promoID)
	return err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT plan_id, plan_name, code, price, duration_months, duration_days, max_users, max_students, whatsapp_credits, features_json, is_trial, is_active, status, created_at FROM subscription_plans WHERE is_active = TRUE ORDER BY price ASC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.PlanID,
			&i.PlanName,
			&i.Code,
			&i.Price,
			&i.DurationMonths,
			&i.DurationDays,
			&i.MaxUsers,
			&i.MaxStudents,
			&i.WhatsappCredits,
			&i.FeaturesJson,
			&i.IsTrial,
			&i.IsActive,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlans = `-- name: ListAllPlans :many
SELECT plan_id, plan_name, code, price, duration_months, duration_days, max_users, max_students, whatsapp_credits, features_json, is_trial, is_active, status, created_at FROM subscription_plans ORDER BY price ASC
`

func (q *Queries) ListAllPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.PlanID,
			&i.PlanName,
			&i.Code,
			&i.Price,
			&i.DurationMonths,
			&i.DurationDays,
			&i.MaxUsers,
			&i.MaxStudents,
			&i.WhatsappCredits,
			&i.FeaturesJson,
			&i.IsTrial,
			&i.IsActive,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
