// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support.sql

package public

import (
	"context"
)

const addTicketReply = `-- name: AddTicketReply :one
INSERT INTO ticket_messages (ticket_id, sender_user_id, is_admin_reply, message, attachment_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticket_id, sender_user_id, is_admin_reply, message, attachment_url, created_on
`

type AddTicketReplyParams struct {
	TicketID      int64
	SenderUserID  int64
	IsAdminReply  bool
	Message       string
	AttachmentUrl *string
}

func (q *Queries) AddTicketReply(ctx context.Context, arg AddTicketReplyParams) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, addTicketReply,
		arg.TicketID,
		arg.SenderUserID,
		arg.IsAdminReply,
		arg.Message,
		arg.AttachmentUrl,
	)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SenderUserID,
		&i.IsAdminReply,
		&i.Message,
		&i.AttachmentUrl,
		&i.CreatedOn,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO support_tickets (tenant_id, user_id, subject, category, priority, description, attachment_url, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'Open')
RETURNING ticket_id, tenant_id, user_id, subject, category, priority, description, attachment_url, status, created_at, updated_at
`

type CreateTicketParams struct {
	TenantID      int64
	UserID        int64
	Subject       string
	Category      *string
	Priority      *string
	Description   *string
	AttachmentUrl *string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.TenantID,
		arg.UserID,
		arg.Subject,
		arg.Category,
		arg.Priority,
		arg.Description,
		arg.AttachmentUrl,
	)
	var i SupportTicket
	err := row.Scan(
		&i.TicketID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Priority,
		&i.Description,
		&i.AttachmentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT ticket_id, tenant_id, user_id, subject, category, priority, description, attachment_url, status, created_at, updated_at FROM support_tickets WHERE ticket_id = $1
`

func (q *Queries) GetTicket(ctx context.Context, ticketID int64) (SupportTicket, error) {
	row := q.db.QueryRow(ctx, getTicket, ticketID)
	var i SupportTicket
	err := row.Scan(
		&i.TicketID,
		&i.TenantID,
		&i.UserID,
		&i.Subject,
		&i.Category,
		&i.Priority,
		&i.Description,
		&i.AttachmentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketMessages = `-- name: ListTicketMessages :many
SELECT id, ticket_id, sender_user_id, is_admin_reply, message, attachment_url, created_on FROM ticket_messages WHERE ticket_id = $1 ORDER BY created_on ASC
`

func (q *Queries) ListTicketMessages(ctx context.Context, ticketID int64) ([]TicketMessage, error) {
	rows, err := q.db.Query(ctx, listTicketMessages, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketMessage{}
	for rows.Next() {
		var i TicketMessage
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SenderUserID,
			&i.IsAdminReply,
			&i.Message,
			&i.AttachmentUrl,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT ticket_id, tenant_id, user_id, subject, category, priority, description, attachment_url, status, created_at, updated_at FROM support_tickets
WHERE ($1::bigint = 0 OR tenant_id = $1)
  AND ($2::text = '' OR status = $2)
ORDER BY updated_at DESC
`

type ListTicketsParams struct {
	TenantID int64
	Status   string
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]SupportTicket, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SupportTicket{}
	for rows.Next() {
		var i SupportTicket
		if err := rows.Scan(
			&i.TicketID,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.Category,
			&i.Priority,
			&i.Description,
			&i.AttachmentUrl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTicket = `-- name: TouchTicket :exec
UPDATE support_tickets SET updated_at = now() WHERE ticket_id = $1
`

func (q *Queries) TouchTicket(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, touchTicket, ticketID)
	return err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE support_tickets SET status = $1, updated_at = now() WHERE ticket_id = $2
`

type UpdateTicketStatusParams struct {
	Status   string
	TicketID int64
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.Exec(ctx, updateTicketStatus, arg.Status, arg.TicketID)
	return err
}
