// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package public

import (
	"context"
	"time"
)

const addDocumentToApplicationType = `-- name: AddDocumentToApplicationType :exec
INSERT INTO application_type_documents (
    application_type_id, document_type_id, display_order, is_required
) VALUES (
    $1, $2, $3, $4
)
`

type AddDocumentToApplicationTypeParams struct {
	ApplicationTypeID int64
	DocumentTypeID    int64
	DisplayOrder      int32
	IsRequired        bool
}

func (q *Queries) AddDocumentToApplicationType(ctx context.Context, arg AddDocumentToApplicationTypeParams) error {
	_, err := q.db.Exec(ctx, addDocumentToApplicationType,
		arg.ApplicationTypeID,
		arg.DocumentTypeID,
		arg.DisplayOrder,
		arg.IsRequired,
	)
	return err
}

const createApplicationType = `-- name: CreateApplicationType :one
INSERT INTO application_types (
    name, description
) VALUES (
    $1, $2
) RETURNING id, name, description, created_at, updated_at
`

type CreateApplicationTypeParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateApplicationType(ctx context.Context, arg CreateApplicationTypeParams) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, createApplicationType, arg.Name, arg.Description)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentType = `-- name: CreateDocumentType :one
INSERT INTO document_types (
    name, description
) VALUES (
    $1, $2
) RETURNING id, name, description, created_at, updated_at, is_active
`

type CreateDocumentTypeParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateDocumentType(ctx context.Context, arg CreateDocumentTypeParams) (DocumentType, error) {
	row := q.db.QueryRow(ctx, createDocumentType, arg.Name, arg.Description)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteApplicationType = `-- name: DeleteApplicationType :exec
DELETE FROM application_types
WHERE id = $1
`

func (q *Queries) DeleteApplicationType(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteApplicationType, id)
	return err
}

const deleteDocumentType = `-- name: DeleteDocumentType :exec
UPDATE document_types
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeleteDocumentType(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentType, id)
	return err
}

const getApplicationType = `-- name: GetApplicationType :one
SELECT id, name, description, created_at, updated_at FROM application_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApplicationType(ctx context.Context, id int64) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, getApplicationType, id)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentType = `-- name: GetDocumentType :one
SELECT id, name, description, created_at, updated_at, is_active FROM document_types
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocumentType(ctx context.Context, id int64) (DocumentType, error) {
	row := q.db.QueryRow(ctx, getDocumentType, id)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getDocumentTypeByName = `-- name: GetDocumentTypeByName :one
SELECT id, name, description, created_at, updated_at, is_active FROM document_types
WHERE name = $1
`

func (q *Queries) GetDocumentTypeByName(ctx context.Context, name string) (DocumentType, error) {
	row := q.db.QueryRow(ctx, getDocumentTypeByName, name)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getDocumentsForApplicationType = `-- name: GetDocumentsForApplicationType :many
SELECT d.id, d.name, d.description, d.created_at, d.updated_at, d.is_active, ad.display_order, ad.is_required
FROM document_types d
JOIN application_type_documents ad ON d.id = ad.document_type_id
WHERE ad.application_type_id = $1
ORDER BY ad.display_order ASC
`

type GetDocumentsForApplicationTypeRow struct {
	ID           int64
	Name         string
	Description  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
	DisplayOrder int32
	IsRequired   bool
}

func (q *Queries) GetDocumentsForApplicationType(ctx context.Context, applicationTypeID int64) ([]GetDocumentsForApplicationTypeRow, error) {
	rows, err := q.db.Query(ctx, getDocumentsForApplicationType, applicationTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentsForApplicationTypeRow{}
	for rows.Next() {
		var i GetDocumentsForApplicationTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
			&i.DisplayOrder,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationTypes = `-- name: ListApplicationTypes :many
SELECT id, name, description, created_at, updated_at FROM application_types
ORDER BY name ASC
`

func (q *Queries) ListApplicationTypes(ctx context.Context) ([]ApplicationType, error) {
	rows, err := q.db.Query(ctx, listApplicationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplicationType{}
	for rows.Next() {
		var i ApplicationType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, name, description, created_at, updated_at, is_active FROM document_types
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListDocumentTypes(ctx context.Context) ([]DocumentType, error) {
	rows, err := q.db.Query(ctx, listDocumentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentType{}
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentsFromApplicationType = `-- name: RemoveDocumentsFromApplicationType :exec
DELETE FROM application_type_documents
WHERE application_type_id = $1
`

func (q *Queries) RemoveDocumentsFromApplicationType(ctx context.Context, applicationTypeID int64) error {
	_, err := q.db.Exec(ctx, removeDocumentsFromApplicationType, applicationTypeID)
	return err
}

const updateApplicationType = `-- name: UpdateApplicationType :one
UPDATE application_types
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at
`

type UpdateApplicationTypeParams struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) UpdateApplicationType(ctx context.Context, arg UpdateApplicationTypeParams) (ApplicationType, error) {
	row := q.db.QueryRow(ctx, updateApplicationType, arg.ID, arg.Name, arg.Description)
	var i ApplicationType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentType = `-- name: UpdateDocumentType :one
UPDATE document_types
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_at, updated_at, is_active
`

type UpdateDocumentTypeParams struct {
	ID          int64
	Name        string
	Description *string
}

func (q *Queries) UpdateDocumentType(ctx context.Context, arg UpdateDocumentTypeParams) (DocumentType, error) {
	row := q.db.QueryRow(ctx, updateDocumentType, arg.ID, arg.Name, arg.Description)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
