// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package public

import (
	"context"
	"time"
)

const addTenantWhatsappBalance = `-- name: AddTenantWhatsappBalance :one
UPDATE tenants
SET whatsapp_balance = COALESCE(whatsapp_balance, 0) + $1, updated_at = now()
WHERE tenant_id = $2
RETURNING tenant_id, tenant_name, company_name, tenant_code, schema_name, subdomain, status, contact_email, contact_phone, logo_url, whatsapp_balance, whatsapp_sent_count, is_active, created_by, updated_by, created_at, updated_at, org_type, kyc_status, kyc_verified_by, kyc_verified_at, kyc_rejected_by, kyc_rejected_at, kyc_rejection_reason, organization_type_id
`

type AddTenantWhatsappBalanceParams struct {
	AmountToAdd *int32
	TenantID    int64
}

func (q *Queries) AddTenantWhatsappBalance(ctx context.Context, arg AddTenantWhatsappBalanceParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, addTenantWhatsappBalance, arg.AmountToAdd, arg.TenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantName,
		&i.CompanyName,
		&i.TenantCode,
		&i.SchemaName,
		&i.Subdomain,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.WhatsappBalance,
		&i.WhatsappSentCount,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgType,
		&i.KycStatus,
		&i.KycVerifiedBy,
		&i.KycVerifiedAt,
		&i.KycRejectedBy,
		&i.KycRejectedAt,
		&i.KycRejectionReason,
		&i.OrganizationTypeID,
	)
	return i, err
}

const countTenants = `-- name: CountTenants :one
SELECT count(*) FROM tenants t
WHERE ($1::text = ''
       OR t.tenant_name ILIKE '%'||$1||'%'
       OR t.company_name ILIKE '%'||$1||'%')
`

func (q *Queries) CountTenants(ctx context.Context, filter string) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (tenant_name, company_name, schema_name, tenant_code, contact_phone, contact_email, org_type, organization_type_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING tenant_id, tenant_name, company_name, tenant_code, schema_name, subdomain, status, contact_email, contact_phone, logo_url, whatsapp_balance, whatsapp_sent_count, is_active, created_by, updated_by, created_at, updated_at, org_type, kyc_status, kyc_verified_by, kyc_verified_at, kyc_rejected_by, kyc_rejected_at, kyc_rejection_reason, organization_type_id
`

type CreateTenantParams struct {
	TenantName         string
	CompanyName        *string
	SchemaName         string
	TenantCode         *string
	ContactPhone       *string
	ContactEmail       *string
	OrgType            *string
	OrganizationTypeID *int64
	CreatedBy          *int64
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.TenantName,
		arg.CompanyName,
		arg.SchemaName,
		arg.TenantCode,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.OrgType,
		arg.OrganizationTypeID,
		arg.CreatedBy,
	)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantName,
		&i.CompanyName,
		&i.TenantCode,
		&i.SchemaName,
		&i.Subdomain,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.WhatsappBalance,
		&i.WhatsappSentCount,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgType,
		&i.KycStatus,
		&i.KycVerifiedBy,
		&i.KycVerifiedAt,
		&i.KycRejectedBy,
		&i.KycRejectedAt,
		&i.KycRejectionReason,
		&i.OrganizationTypeID,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT tenant_id, tenant_name, company_name, tenant_code, schema_name, subdomain, status, contact_email, contact_phone, logo_url, whatsapp_balance, whatsapp_sent_count, is_active, created_by, updated_by, created_at, updated_at, org_type, kyc_status, kyc_verified_by, kyc_verified_at, kyc_rejected_by, kyc_rejected_at, kyc_rejection_reason, organization_type_id FROM tenants WHERE tenant_id = $1
`

func (q *Queries) GetTenant(ctx context.Context, tenantID int64) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, tenantID)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantName,
		&i.CompanyName,
		&i.TenantCode,
		&i.SchemaName,
		&i.Subdomain,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.WhatsappBalance,
		&i.WhatsappSentCount,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgType,
		&i.KycStatus,
		&i.KycVerifiedBy,
		&i.KycVerifiedAt,
		&i.KycRejectedBy,
		&i.KycRejectedAt,
		&i.KycRejectionReason,
		&i.OrganizationTypeID,
	)
	return i, err
}

const getTenantBySchema = `-- name: GetTenantBySchema :one
SELECT tenant_id, tenant_name, company_name, tenant_code, schema_name, subdomain, status, contact_email, contact_phone, logo_url, whatsapp_balance, whatsapp_sent_count, is_active, created_by, updated_by, created_at, updated_at, org_type, kyc_status, kyc_verified_by, kyc_verified_at, kyc_rejected_by, kyc_rejected_at, kyc_rejection_reason, organization_type_id FROM tenants WHERE schema_name = $1
`

func (q *Queries) GetTenantBySchema(ctx context.Context, schemaName string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySchema, schemaName)
	var i Tenant
	err := row.Scan(
		&i.TenantID,
		&i.TenantName,
		&i.CompanyName,
		&i.TenantCode,
		&i.SchemaName,
		&i.Subdomain,
		&i.Status,
		&i.ContactEmail,
		&i.ContactPhone,
		&i.LogoUrl,
		&i.WhatsappBalance,
		&i.WhatsappSentCount,
		&i.IsActive,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgType,
		&i.KycStatus,
		&i.KycVerifiedBy,
		&i.KycVerifiedAt,
		&i.KycRejectedBy,
		&i.KycRejectedAt,
		&i.KycRejectionReason,
		&i.OrganizationTypeID,
	)
	return i, err
}

const getTenantStats = `-- name: GetTenantStats :one
SELECT count(*)::bigint AS total_tenants,
       count(*) FILTER (WHERE is_active)::bigint AS active_tenants,
       COALESCE(sum(whatsapp_balance), 0)::bigint AS total_balance
FROM tenants
`

type GetTenantStatsRow struct {
	TotalTenants  int64
	ActiveTenants int64
	TotalBalance  int64
}

func (q *Queries) GetTenantStats(ctx context.Context) (GetTenantStatsRow, error) {
	row := q.db.QueryRow(ctx, getTenantStats)
	var i GetTenantStatsRow
	err := row.Scan(&i.TotalTenants, &i.ActiveTenants, &i.TotalBalance)
	return i, err
}

const listAllTenantSchemas = `-- name: ListAllTenantSchemas :many
SELECT tenant_id, schema_name FROM tenants ORDER BY tenant_id
`

type ListAllTenantSchemasRow struct {
	TenantID   int64
	SchemaName string
}

func (q *Queries) ListAllTenantSchemas(ctx context.Context) ([]ListAllTenantSchemasRow, error) {
	rows, err := q.db.Query(ctx, listAllTenantSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTenantSchemasRow{}
	for rows.Next() {
		var i ListAllTenantSchemasRow
		if err := rows.Scan(&i.TenantID, &i.SchemaName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT t.tenant_id, t.tenant_name, t.company_name, t.tenant_code, t.schema_name, t.subdomain, t.status, t.contact_email, t.contact_phone, t.logo_url, t.whatsapp_balance, t.whatsapp_sent_count, t.is_active, t.created_by, t.updated_by, t.created_at, t.updated_at, t.org_type, t.kyc_status, t.kyc_verified_by, t.kyc_verified_at, t.kyc_rejected_by, t.kyc_rejected_at, t.kyc_rejection_reason, t.organization_type_id,
    COALESCE(to_char(s.end_date, 'YYYY-MM-DD'), '')::text AS subscription_end_date,
    COALESCE(s.status, '')::text AS subscription_status
FROM tenants t
LEFT JOIN (
    SELECT DISTINCT ON (tenant_id) tenant_id, end_date, status
    FROM tenant_subscriptions
    ORDER BY tenant_id, end_date DESC
) s ON s.tenant_id = t.tenant_id
WHERE ($1::text = ''
       OR t.tenant_name ILIKE '%'||$1||'%'
       OR t.company_name ILIKE '%'||$1||'%')
ORDER BY t.tenant_id ASC
LIMIT $3 OFFSET $2
`

type ListTenantsParams struct {
	Filter string
	Off    int32
	Lim    int32
}

type ListTenantsRow struct {
	TenantID            int64
	TenantName          string
	CompanyName         *string
	TenantCode          *string
	SchemaName          string
	Subdomain           *string
	Status              string
	ContactEmail        *string
	ContactPhone        *string
	LogoUrl             *string
	WhatsappBalance     *int32
	WhatsappSentCount   int64
	IsActive            bool
	CreatedBy           *int64
	UpdatedBy           *int64
	CreatedAt           time.Time
	UpdatedAt           *time.Time
	OrgType             *string
	KycStatus           string
	KycVerifiedBy       *int64
	KycVerifiedAt       *time.Time
	KycRejectedBy       *int64
	KycRejectedAt       *time.Time
	KycRejectionReason  *string
	OrganizationTypeID  *int64
	SubscriptionEndDate string
	SubscriptionStatus  string
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]ListTenantsRow, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Filter, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsRow{}
	for rows.Next() {
		var i ListTenantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.CompanyName,
			&i.TenantCode,
			&i.SchemaName,
			&i.Subdomain,
			&i.Status,
			&i.ContactEmail,
			&i.ContactPhone,
			&i.LogoUrl,
			&i.WhatsappBalance,
			&i.WhatsappSentCount,
			&i.IsActive,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgType,
			&i.KycStatus,
			&i.KycVerifiedBy,
			&i.KycVerifiedAt,
			&i.KycRejectedBy,
			&i.KycRejectedAt,
			&i.KycRejectionReason,
			&i.OrganizationTypeID,
			&i.SubscriptionEndDate,
			&i.SubscriptionStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTenantID = `-- name: MaxTenantID :one
SELECT COALESCE(max(tenant_id), 0)::bigint FROM tenants
`

func (q *Queries) MaxTenantID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, maxTenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setTenantSchemaName = `-- name: SetTenantSchemaName :exec
UPDATE tenants SET schema_name = $1 WHERE tenant_id = $2
`

type SetTenantSchemaNameParams struct {
	SchemaName string
	TenantID   int64
}

func (q *Queries) SetTenantSchemaName(ctx context.Context, arg SetTenantSchemaNameParams) error {
	_, err := q.db.Exec(ctx, setTenantSchemaName, arg.SchemaName, arg.TenantID)
	return err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :exec
UPDATE tenants SET is_active = $1,
    status = CASE WHEN $1::bool THEN 'Active' ELSE 'Suspended' END,
    updated_at = now()
WHERE tenant_id = $2
`

type UpdateTenantStatusParams struct {
	IsActive bool
	TenantID int64
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) error {
	_, err := q.db.Exec(ctx, updateTenantStatus, arg.IsActive, arg.TenantID)
	return err
}
