// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package public

import (
	"context"
)

const countTenantUsers = `-- name: CountTenantUsers :one
SELECT count(*)
FROM users u
JOIN user_tenants ut ON ut.user_id = u.id
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE ut.tenant_id = $1
  AND u.deleted_at IS NULL
  AND ($2::text = '' OR u.email ILIKE '%'||$2||'%' OR up.first_name ILIKE '%'||$2||'%' OR up.last_name ILIKE '%'||$2||'%')
`

type CountTenantUsersParams struct {
	TenantID int64
	Filter   string
}

func (q *Queries) CountTenantUsers(ctx context.Context, arg CountTenantUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantUsers, arg.TenantID, arg.Filter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, google_id, is_active, is_verified, is_superadmin)
VALUES (lower($1), $2, $3, $4, $5, COALESCE($6, FALSE))
RETURNING id, email, password_hash, google_id, is_active, is_verified, last_login_at, created_at, updated_at, deleted_at, user_type, is_superadmin
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	GoogleID     *string
	IsActive     bool
	IsVerified   bool
	IsSuperadmin interface{}
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleID,
		arg.IsActive,
		arg.IsVerified,
		arg.IsSuperadmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserType,
		&i.IsSuperadmin,
	)
	return i, err
}

const getTenantUser = `-- name: GetTenantUser :one
SELECT u.id, u.email AS username, COALESCE(r.role_name, '') AS role,
       u.is_active, ut.tenant_id, ut.status AS membership_status, ut.is_owner,
       up.first_name, up.last_name, up.contact_number
FROM users u
JOIN user_tenants ut ON ut.user_id = u.id
LEFT JOIN roles r ON r.role_id = ut.role_id
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE u.id = $1 AND ut.tenant_id = $2 AND u.deleted_at IS NULL
`

type GetTenantUserParams struct {
	UserID   int64
	TenantID int64
}

type GetTenantUserRow struct {
	ID               int64
	Username         string
	Role             string
	IsActive         bool
	TenantID         int64
	MembershipStatus string
	IsOwner          bool
	FirstName        *string
	LastName         *string
	ContactNumber    *string
}

func (q *Queries) GetTenantUser(ctx context.Context, arg GetTenantUserParams) (GetTenantUserRow, error) {
	row := q.db.QueryRow(ctx, getTenantUser, arg.UserID, arg.TenantID)
	var i GetTenantUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.IsActive,
		&i.TenantID,
		&i.MembershipStatus,
		&i.IsOwner,
		&i.FirstName,
		&i.LastName,
		&i.ContactNumber,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, google_id, is_active, is_verified, last_login_at, created_at, updated_at, deleted_at, user_type, is_superadmin FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserType,
		&i.IsSuperadmin,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, google_id, is_active, is_verified, last_login_at, created_at, updated_at, deleted_at, user_type, is_superadmin FROM users WHERE google_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserType,
		&i.IsSuperadmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, google_id, is_active, is_verified, last_login_at, created_at, updated_at, deleted_at, user_type, is_superadmin FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleID,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserType,
		&i.IsSuperadmin,
	)
	return i, err
}

const listTenantUserLookup = `-- name: ListTenantUserLookup :many
SELECT u.id AS user_id, COALESCE(NULLIF(trim(coalesce(p.first_name,'')||' '||coalesce(p.last_name,'')), ''), u.email) AS display_name,
       COALESCE(r.role_name, '') AS role_name
FROM users u
JOIN user_tenants ut ON ut.user_id = u.id
LEFT JOIN roles r ON r.role_id = ut.role_id
LEFT JOIN user_profiles p ON p.user_id = u.id
WHERE ut.tenant_id = $1 AND u.deleted_at IS NULL AND u.is_active = TRUE
ORDER BY display_name ASC
`

type ListTenantUserLookupRow struct {
	UserID      int64
	DisplayName string
	RoleName    string
}

func (q *Queries) ListTenantUserLookup(ctx context.Context, tenantID int64) ([]ListTenantUserLookupRow, error) {
	rows, err := q.db.Query(ctx, listTenantUserLookup, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUserLookupRow{}
	for rows.Next() {
		var i ListTenantUserLookupRow
		if err := rows.Scan(&i.UserID, &i.DisplayName, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT u.id, u.email AS username, COALESCE(r.role_name, '') AS role,
       u.is_active, ut.tenant_id, ut.status AS membership_status, ut.is_owner,
       up.first_name, up.last_name, up.contact_number
FROM users u
JOIN user_tenants ut ON ut.user_id = u.id
LEFT JOIN roles r ON r.role_id = ut.role_id
LEFT JOIN user_profiles up ON up.user_id = u.id
WHERE ut.tenant_id = $1
  AND u.deleted_at IS NULL
  AND ($2::text = '' OR u.email ILIKE '%'||$2||'%' OR up.first_name ILIKE '%'||$2||'%' OR up.last_name ILIKE '%'||$2||'%')
ORDER BY u.email ASC
LIMIT $4 OFFSET $3
`

type ListTenantUsersParams struct {
	TenantID int64
	Filter   string
	Off      int32
	Lim      int32
}

type ListTenantUsersRow struct {
	ID               int64
	Username         string
	Role             string
	IsActive         bool
	TenantID         int64
	MembershipStatus string
	IsOwner          bool
	FirstName        *string
	LastName         *string
	ContactNumber    *string
}

func (q *Queries) ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers,
		arg.TenantID,
		arg.Filter,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.IsActive,
			&i.TenantID,
			&i.MembershipStatus,
			&i.IsOwner,
			&i.FirstName,
			&i.LastName,
			&i.ContactNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserVerified = `-- name: MarkUserVerified :exec
UPDATE users SET is_verified = TRUE, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkUserVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markUserVerified, id)
	return err
}

const setUserGoogleID = `-- name: SetUserGoogleID :exec
UPDATE users SET google_id = $1, updated_at = now() WHERE id = $2
`

type SetUserGoogleIDParams struct {
	GoogleID *string
	ID       int64
}

func (q *Queries) SetUserGoogleID(ctx context.Context, arg SetUserGoogleIDParams) error {
	_, err := q.db.Exec(ctx, setUserGoogleID, arg.GoogleID, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $1, is_verified = TRUE, updated_at = now()
WHERE id = $2
`

type SetUserPasswordParams struct {
	PasswordHash *string
	ID           int64
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users SET is_active = $1, updated_at = now() WHERE id = $2
`

type UpdateUserActiveParams struct {
	IsActive bool
	ID       int64
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.Exec(ctx, updateUserActive, arg.IsActive, arg.ID)
	return err
}
